tpatalas/tp-next-todos

deploy.sh
Now `deploy.sh` will pick up any environment variable with the prefix `GCR_`. Any environment variable name with the prefix will be saved into Google Cloud Run's environment variable.
This improves the developer experience dramatically because environment variable does not need to be defined with `deploy.sh` manually whenever a new variable is added.
=> feat: add auto-pick of environment variables by `deploy.sh`

components/auth/authForm.tsx, components/layouts/layoutApp/layout/layoutHeader/index.tsx, lib/dataConnections/indexedDB.ts, lib/states/effects/atomEffects.tsx, lib/states/effects/queryEffects.tsx, lib/states/todos/filterTodoIdsEffect.tsx, lib/states/users/index.tsx, lib/states/users/userSessionEffect.tsx, lib/types/index.ts, middleware.ts
Enhance rendering with middleware to ensure smooth UI rendering. Additionally, fix the mobile view rendering issue where the label list is infinitely requesting to fetch the item due to `useRecoilCallback`. The `useRecoilCallback` has continuously attempted to retrieve the label list since the mobile view  hides the label menu.
=> feat: improve rendering using middleware

components/ui/buttons/iconButton/index.tsx, components/ui/dropdowns/v1/labelComboBoxDropdown.tsx, lib/data/dataOptions.tsx, lib/data/stylePreset.tsx
Increase the intensity of the background color of labels and remove the color of the text for consistent rendering. The default label color has been updated from the presetStyle.
=> feat: revised label colors

components/ui/dropdowns/v1/labelComboBoxDropdown.tsx, components/ui/tooltips/tooltips/index.tsx, lib/data/stylePreset.tsx
Improve the tooltip shown in the labelComboBoxDropdown by truncating long label names. This tooltip is particularly important because labels themselves have a maximum width of 5.3rem.
Fix minor inconsistencies in the styling of buttons' presetStyle.
=> feat: improve the tooltip and fix minor style inconsistencies

components/ui/buttons/iconButton/index.tsx, components/ui/dropdowns/v1/labelComboBoxDropdown.tsx, components/ui/modals/todoModals/todoModal/index.tsx, components/ui/tooltips/tooltips/index.tsx, lib/data/dataOptions.tsx, lib/data/stylePreset.tsx
Improve the styles on labels, tooltip, and button, and fix the minor issues
- feat: update the rendering and new style on labels (#362)
- feat: revised label colors (#364)
- feat: improve the tooltip and fix minor style inconsistencies (#365)
=> feat: improve the styles and renderings

components/todos/todoList.tsx, components/ui/dropdowns/v2/userDropdown.tsx
Fixed the misconfiguration of Next.js's Image component. Added the fixed width and auth-height of the images and set the priority. Also added priority to the avatar image.
=> fix: fix the next.js's Image component configurations

components/todos/todo/todoItem.tsx, components/todos/todoList.tsx, components/ui/dropdowns/v1/labelComboBoxDropdown.tsx, components/ui/gradients/labelsHorizontalGradients.tsx, components/ui/modals/todoModals/todoModal/index.tsx, tailwind.config.js
Improve the UI rendering based on different media queries. Add new screen sizes to tailwind.config.js and implement dynamic width for labels based on the new screen sizes.
=> feat: improve ui rendering and update tailwind.config

components/layouts/layoutApp/layout/layoutFooter/footerSidebar/index.tsx, components/layouts/layoutApp/layout/layoutHeader/headerUser.tsx, components/layouts/layoutApp/layoutLogo.tsx, lib/states/users/index.tsx
The following quick fixes have been made to correct the mobile view:
- fix: the issue where the logo does not render correctly on the mobile view has been resolved.
- fix: the padding bottom of the mobile menu has been increased to show the footerSidebar menu correctly on mobile.
- fix: fix the userAvatar flickering.
=> fix: fix the ui rendering issues on mobile

components/ui/dropdowns/v1/todoItemDropdown.tsx, components/ui/inputs/checkbox.tsx, components/ui/modals/todoModals/todoModal/todoModalHeaderButtons.tsx, lib/data/dataOptions.tsx
Previously, the kbd did not render correctly for mobile devices, which could cause confusion for users. This fix ensures that mobile devices do not display the keyboard shortcuts intended for desktop devices.
With this update, the keyboard shortcuts will only be visible on desktop devices, which will provide a better user experience for both desktop and mobile users.
=> fix: correctly render keyboard shortcuts for different device types

components/layouts/layoutApp/layoutLogo.tsx, components/ui/buttons/iconButton/index.tsx
Perform minor refactoring to enhance markup validation after encountering a few minor errors. These changes do not affect the application's structure or functionality.
=> refactor: improve markup validation

components/layouts/layoutApp/layout/layoutFooter/footerSidebar/index.tsx, components/layouts/layoutApp/layout/layoutFooter/index.tsx, components/ui/comboBoxes/comboBox/index.tsx, components/ui/comboBoxes/labelComboBox.tsx, components/ui/dropdowns/v1/dropdown/index.tsx, components/ui/dropdowns/v2/dropdown/menuItems.tsx, components/ui/gradients/globalVerticalGradient.tsx, components/ui/gradients/labelsHorizontalGradients.tsx, components/ui/inputs/floatingLabelInput.tsx, components/ui/modals/modal/modalTransition/minimizeModalTransition.tsx, components/ui/modals/modal/modalTransition/modalTransitionChild.tsx, components/ui/pseudoButtons/pseudoIconButton/index.tsx, lib/data/dataTypesConst.tsx, lib/types/index.ts
Introduce the `GlobalVerticalGradient` component for dynamic vertical gradient effects. This component supports both single and double gradient types and can be positioned at the top or bottom.
Refactor the `footerBody` background color from white to transparent for consistency and enhance the box shadow effect.
=> feat: add `GlobalVerticalGradient` component and refactor styles

components/auth/authErrorMessage.tsx, components/auth/authForm.tsx, components/layouts/layoutApp/layoutLogo.tsx, components/loadable/loadingSpinner/index.tsx
Address and fix the issues identified by the W3C Markup Validation Service to ensure the HTML markup is compliant with web standards.
=> fix: resolve  markup validation issues

components/auth/authForm.tsx, components/layouts/layoutApp/layout/layoutFooter/index.tsx, components/layouts/layoutApp/layoutLogo.tsx, components/todos/todo/todoItemFocuser.tsx, components/ui/dividers/divider/index.tsx, components/ui/gradients/globalVerticalGradient.tsx, components/ui/inputs/checkbox.tsx, components/ui/inputs/floatingLabelInput.tsx, components/ui/modals/labelModals/labelModal/index.tsx, lib/data/dataArrayOfObjects.tsx, lib/data/stylePreset.tsx
This commit addresses some subtle CSS inconsistencies in the codebase. The one of the main issue was an unmatched background color after the main background color was changed to `bg-slate-50`. Some elements still had a white background color.
In addition, some minor styles were re-touched without impacting any other changes. Overall, these changes improve the consistency and visual coherence of the application's design.
=> refactor: fix CSS inconsistencies

components/layouts/layoutApp/layout/layoutFooter/footerSidebar/index.tsx, components/layouts/layoutApp/layout/layoutFooter/index.tsx, components/ui/backdrops/backdrop/index.tsx, components/ui/gradients/globalVerticalGradient.tsx
This commit includes the following style updates:
- Increase the z-index of `footerSidebar` and `backdrop` by 10 to improve layering.
- Increase the `padding-top` of `footerBody` for better spacing.
- Add dynamic height for the vertical gradient top, adjusting based on mobile devices for improved responsiveness.
=> refactor: Update styles

components/layouts/app/appNavigation/appSidebarMenu.tsx, components/layouts/home/homeNavigation.tsx, components/layouts/home/index.tsx, components/layouts/layoutFooter/footerNavigation.tsx, components/layouts/layoutFooter/index.tsx, components/layouts/layoutHeader/index.tsx, components/ui/backdrops/backdrop/index.tsx, lib/types/bases/ui.ts
This update correctly renders and fixes the minor issues that arises when showing the navigation menu on home layout.
=> feat: update the footer layout for Home layout

components/auth/authForm.tsx, components/layouts/layoutHeader/index.tsx, components/layouts/layoutHeader/user.tsx, lib/data/constAssertions/data.tsx, lib/stateLogics/effects/userSessionEffect.tsx, lib/stateLogics/effects/userSessionResetEffect.tsx, lib/stateLogics/states/users.tsx, lib/stateLogics/utils/index.tsx, middleware.ts, pages/_app.tsx, pages/demo/index.tsx
Add demo page for users to access features without signing up. Implement middleware protection to redirect users from protected areas based on their session status.
Fix minor issues in PATH_HOME by removing whitespace that affects pathname checking.
Reduce flickering in userAvatar component.
=> feat: add demo page

components/ui/modals/labelModals/labelModal/index.tsx, lib/stateLogics/effects/filterTodoIdsEffect.tsx
Enhance the code quality by removing unused sections and abstracting repetitive patterns. This change focuses on improving readability and maintainability without introducing new functionality.
=> feat: enhance code readability and maintainability

components/layouts/app/index.tsx, components/layouts/home/index.tsx, lib/data/constAssertions/data.tsx, lib/stateLogics/effects/filters/filterPathAppEffect.tsx, lib/stateLogics/effects/filters/filterPathHomeEffect.tsx, lib/stateLogics/states/misc.tsx, lib/stateLogics/states/todos.tsx, pages/app/[appId].tsx, pages/app/index.tsx, pages/app/label/[labelId].tsx, pages/auth/index.tsx, pages/features/index.tsx, pages/implementations/index.tsx, pages/pricing/index.tsx
Implement dynamic HTML title rendering for each page based on the page's route. This addition ensures that the title tag and favicon are displayed properly. The titles are generated using the FilterPathAppEffect or FilterPathHomeEffect, depending on the route.
=> feat: dynamically generate HTML titles for each page

components/layouts/layoutHeader/signInButton.tsx, lib/stateLogics/effects/filterTodoIdsEffect.tsx, lib/types/bases/ui.ts
Improve the signInButton component by accepting an optional object props, making it more reusable. Add signInButtonName prop, including its types.
Resolve minor conflicts resulting from merged branches.
=> refactor: enhance signInButton reusability

components/layouts/layoutHeader/index.tsx, components/layouts/layoutHeader/signInButton.tsx
Tweak the CSS and styling across the application to elevate visual appearance. These subtle adjustments ensure a cohesive look while staying true to the existing design language.
=> feat: refine CSS and styling

components/layouts/home/homeNavigation.tsx, components/layouts/layoutHeader/index.tsx, components/layouts/layoutHeader/signInButton.tsx, components/sections/hero.tsx, components/todos/todoList.tsx, lib/data/stylePreset.tsx, lib/types/options/index.ts
Refactor the hero section component and integrate it into the /index page. The updated hero section is designed to be more static than dynamic, enabling effective caching of the HTML page.
=> feat: improve and integrate hero section component

components/auth/authForm.tsx, components/layouts/home/homeNavigation.tsx, components/ui/dividers/dividerX.tsx, components/ui/dividers/dividerY.tsx, components/ui/modals/labelModals/labelModal/index.tsx, components/ui/modals/todoModals/todoModal/index.tsx
Introduce DividerY component for vertical dividers, rename existing Divider to DividerX for clarity, and move both components to a new 'dividers' directory for improved maintainability.
=> feat: add new vertical divider component

components/sections/footer.tsx, lib/data/collections/footer.tsx
Update the Footer section component by replacing the Link component with IconButton component for the social icon button. Additionally, re-adjust the footer items rendering for better responsiveness across different media queries. No major functional changes have been made.
=> feat: enhance the Footer section component rendering

components/layouts/home/index.tsx, components/layouts/layoutFooter/index.tsx, pages/index.tsx
Incorporate the Footer section component into LayoutHome, ensuring it is rendered on every page within the home layout. The Footer section component has not been added to LayoutApp, as it is not required within that layout.
=> feat: integrate Footer component into LayoutHome

components/layouts/layoutHeader/index.tsx, components/sections/header.tsx, components/sections/hero.tsx, lib/data/stylePreset.tsx, pages/index.tsx, tailwind.config.ts
Create a new HeaderSection component for the index page, which dynamically renders the header based on the user's scroll position. Mobile version optimizations have been included.
=> feat: implement dynamic HeaderSection component

components/sections/header.tsx, lib/stateLogics/hooks/misc.tsx, pages/index.tsx
Improve the rendering of the Header section component across different media queries by utilizing a new custom hook. This hook returns the current client screen width, which can be used within the Header section component to optimize its layout and responsiveness.
=> feat: optimize Header section component rendering

components/auth/authForm.tsx, components/layouts/home/homeNavigation.tsx, components/layouts/layoutHeader/index.tsx
Improve the overall appearance and user experience of the application by adding backdrop-blur to layoutHeader for enhanced scrolling experience, adjusting authForm positioning for better layout consistency, and fixing the layoutHome logo rendering issue.
=> feat: enhance rendering and authForm positioning

components/sections/homeHeader.tsx
Increases the height of the HomeHeader section component to improve the rendering and style of the header. Additionally, the scroll position is re-computed to properly accompany the new rendering timing.
=> feat: increase height of HomeHeader section component

components/sections/homeContent/index.tsx
Refactor homeContent component to render differently on smaller screens. Improve text readability, spacing, and alignment to ensure a better user experience. This change enhances the responsiveness of the app and makes it more accessible on a wider range of devices.
=> refactor: Optimize rendering of homeContent component

components/sections/homeContent/contentText.tsx, components/sections/homeContent/index.tsx, components/sections/homeHeader.tsx, components/sections/homeHero.tsx, lib/data/stylePreset.tsx, lib/stateLogics/hooks/misc.tsx, lib/stateLogics/utils/index.tsx
Update HomeContent by incorporating scroll position-based runtime styles through a new custom hook. The hook delivers flexibility by enabling dynamic scroll position values to be displayed with or without a percentage, accommodating a wide range of use cases.
=> feat: enhance HomeContent with scroll-based runtime styles

components/sections/homeContent/index.tsx, lib/stateLogics/hooks/misc.tsx, lib/stateLogics/hooks/ui.tsx
Enhance the rendering experience on different devices, with a focus on better support for smaller devices with narrower client widths.
Additionally, custom hooks from the misc file have been relocated to the UI custom hooks file for better organization and consistency.
=> feat: improve rendering across various media queries

components/sections/homeContent/index.tsx, lib/data/collections/footer.tsx, lib/stateLogics/hooks/ui.tsx
Abstracts reusable code in the HomeContent component with the use of a custom hook, useScrollPositionRateData(), and an array of objects, DATA_FOOTER_SCROLL_RATE. This improves the readability and maintainability of the code, while reducing the overall length of the HomeContent component. The use of a custom hook also makes it easier to reuse this functionality in other parts of the application.
=> refactor: abstract reusable code in HomeContent

components/sections/underConstruction/index.tsx
Change paragraph elements to heading elements for better semantic structure, adjust padding for improved layout and spacing, and modify text size for better readability and visual hierarchy.
=> feat: update typography and layout styling

components/layouts/home/homeNavigation.tsx, components/layouts/layoutFooter/footerBody.tsx, components/layouts/layoutHeader/logo.tsx
Optimize the sidebar opening by preventing the resetting of the sidebar when the breakpoint is lower than the media queries of 768px. This can prevent any unwanted resetting of the sidebar open in a larger screen size, resulting in a better user experience.
=> feat: optimize Sidebar Open to Prevent Resetting Below 768px

pages/index.tsx
Optimize the initial loading time by using a dynamic import for the HomeStartToday section component on the index page. This enhancement improves performance and provides a better user experience.
=> feat: implement dynamic import for HomeStartToday component

components/auth/authForm.tsx, components/layouts/layoutHeader/logo.tsx, lib/data/collections/svgLogo.tsx, lib/types/bases/data.ts
Introduce new conditional props in the Logo component to support rendering alternative logo types, such as icon-only logos. This enhancement improves the design and user experience.
Incorporate the updated Logo component into the AuthForm to further optimize the UI.
=> feat: Add new  props to Logo  and integrate into AuthForm

Dockerfile, components/layouts/layoutHeader/logo.tsx, components/sections/footer.tsx, components/ui/dropdowns/v2/userDropdown.tsx, pages/_app.tsx
- Add missing link component to social button in Footer section.
- Refactor logo to prevent routing when user is in session.
- Implement cursor event with dynamic classNames for logo.
- Update DockerFile to include node_modules and .next paths to fix external URL image rendering issue with Image component.
=> fix: resolve link-related issues in Footer and DockerFile

components/auth/authForm.tsx
Re-adjusted the CSS to correcly render the authForm on the smaller screen of mobile device.
=> fix: minor adjustment of CSS to correctly render authForm

components/layouts/layoutHeader/user.tsx, components/loadable/loadingStates/loadingLabels.tsx, components/loadable/loadingStates/loadingTodos.tsx, components/sections/homeHero.tsx, components/ui/transitions/smoothTransition.tsx, pages/_app.tsx, pages/_document.tsx
Implement SmoothTransition component for smoother rendering and transition animations on component mount. Move viewport metatag from _document to _app for proper meta rendering.
=> fix: eliminate element flashing in index and app pages

components/sections/homeContent/contentText.tsx, components/sections/homeHero.tsx, tailwind.config.ts
Enhance CSS transformation performance by incorporating the will-change-transform class from Tailwind. This prepares elements for transformation, resulting in smoother and optimized transitions, particularly on mobile devices.
Additionally, adjust the timing of the animation typing for a better user experience.
=> feat: improve CSS performance with will-change-transform

.eslintrc.json, components/editors/editorComposer/index.tsx, components/editors/todoEditor.tsx, components/layouts/app/index.tsx, components/todos/todo/todoItemFocuser.tsx, components/ui/buttons/iconButton/priorityButton.tsx, components/ui/calendars/calendar/index.tsx, components/ui/dropdowns/v1/calendarDropdown.tsx, components/ui/dropdowns/v1/labelComboBoxDropdown.tsx, components/ui/dropdowns/v1/todoItemDropdown.tsx, components/ui/modals/confirmModal/index.tsx, components/ui/modals/labelModals/labelModal/index.tsx, components/ui/modals/labelModals/labelModal/itemLabelModal.tsx, components/ui/modals/modal/modalTransition/modalTransitionChild.tsx, components/ui/modals/todoModals/itemTodoModal.tsx, components/ui/modals/todoModals/todoModal/index.tsx, components/ui/transitions/smoothTransition/index.tsx, components/ui/transitions/smoothTransition/smoothTransition.data.ts, lib/stateLogics/hooks/keybindings.tsx, lib/stateLogics/hooks/misc.tsx, lib/stateLogics/hooks/ui.tsx, lib/stateLogics/states/atomEffects/todos.tsx, package-lock.json, package.json
Add the new package called eslint-plugin-react-hooks to get a better senes of react hook's rules and add the additional hooks for Recoil and React.
Fix the all the violations of rules of react hooks, and made minor changes for todoModal's rendering. No major changes have been changed.
=> fix: fix violations of rule of hooks and additional changes

components/todos/todo/todoItemFocuser.tsx, components/ui/modals/labelModals/labelModal/index.tsx, components/ui/modals/labelModals/labelModal/itemLabelModal.tsx, components/ui/modals/modal/modalTransition/modalTransitionChild.tsx, components/ui/modals/todoModals/itemTodoModal.tsx, components/ui/transitions/smoothTransition/smoothTransition.data.ts
Leverage transform-gpu to utilize hardware acceleration for improving the transitions in the Transition component of Headless UI. Refine the todoModal transition to enhance user experience.
=> feat: Enhance transitions for todoModal and Transition

.eslintrc.json, components/editors/editorComposer/index.tsx, components/ui/buttons/iconButton/priorityButton.tsx, components/ui/calendars/calendar/index.tsx, components/ui/dropdowns/v1/calendarDropdown.tsx, components/ui/dropdowns/v1/labelComboBoxDropdown.tsx, components/ui/dropdowns/v1/todoItemDropdown.tsx, components/ui/modals/confirmModal/index.tsx, components/ui/modals/labelModals/labelModal/index.tsx, components/ui/transitions/smoothTransition/index.tsx, lib/stateLogics/hooks/keybindings.tsx, lib/stateLogics/hooks/misc.tsx, lib/stateLogics/hooks/ui.tsx, package-lock.json, package.json
Install eslint-plugin-react-hooks package for enforcing hook rules, and address and resolve all existing rule of hooks violations in the codebase
=> chore: enforce and resolve ESLint rule of hooks violations

.eslintrc.json, components/editors/editorComposer/index.tsx, components/todos/todo/todoItemFocuser.tsx, components/ui/buttons/iconButton/priorityButton.tsx, components/ui/calendars/calendar/index.tsx, components/ui/dropdowns/v1/calendarDropdown.tsx, components/ui/dropdowns/v1/labelComboBoxDropdown.tsx, components/ui/dropdowns/v1/todoItemDropdown.tsx, components/ui/modals/confirmModal/index.tsx, components/ui/modals/labelModals/labelModal/index.tsx, components/ui/modals/labelModals/labelModal/itemLabelModal.tsx, components/ui/modals/modal/modalTransition/modalTransitionChild.tsx, components/ui/modals/todoModals/itemTodoModal.tsx, components/ui/transitions/smoothTransition/index.tsx, components/ui/transitions/smoothTransition/smoothTransition.data.ts, lib/stateLogics/hooks/keybindings.tsx, lib/stateLogics/hooks/misc.tsx, lib/stateLogics/hooks/ui.tsx, package-lock.json, package.json
Merging develop branch into master branch. Minor update and fix some violation of rule of hooks.
- Enhance transitions for todoModal and Transition. 
- enforce and resolve ESLint rule of hooks violations.
=> refactor(merge): Integrate enhancements for hooks and transitions

components/sections/homeContent/index.tsx, components/sections/homeHeader.tsx, components/sections/homeHero.tsx, components/sections/homeStartToday.tsx, pages/index.tsx
Add the wrapper to the page index and add a section element to the section components. Adjust the transition type on the 'Get started' button in homeHero for better consistency. Also, add SmoothTransition components to the homeStartToday section component to enhance user experience. The transition rate for SmoothTransition is set to 0.7 for a slower transition trigger.
=> feat: update on sections with additional SmoothTransition

__mock__/next-auth/index.ts, __mock__/next/index.ts, components/users/user/__test__/user.test.tsx, components/users/user/userDropdown/__test__/userDropdown.test.tsx, components/users/user/userDropdown/index.tsx, components/users/userSessionGroupEffect/userSessionEffect/__test__/userSessionEffect.test.tsx, lib/stateLogics/utils/index.tsx, package-lock.json, package.json
Add more unit tests for the User component to increase code coverage. Additionally, it includes the mockedImage function to mock the optimized image URL and the mockedSession function to mock the session, both located in the 'mock' directory. This allows for better control and predictability in the testing environment.
=> test: Add more tests for the User component

components/ui/modals/todoModals/todoModal/index.tsx
Optimize transformed element rendering by applying the 'will-change-transform' class to transitioning elements. This mitigates element shifting upon transformation completion.
=> feat: enhance transformed element rendering

components/layouts/home/index.tsx, components/layouts/layoutFooter/footerBody.tsx, components/sections/homeContent/index.tsx, components/sections/homeHeader.tsx, components/sections/homeHero.tsx, components/sections/homeStartToday.tsx, pages/index.tsx
Resolve minor HTML markup validator issues. These fixes improve the overall validation and markup quality.
=> fix: Address various validator issues

cloudbuild.yaml
Add cloudbuild.yaml for initiating CI/CD pipeline. Note: current implementation supports only CD without automatic testing.
=> feat: Introduce CloudBuild

.github/workflows/create-develop-branch.yml
Implements a workflow to seamlessly restore the 'develop' branch whenever it gets deleted. This strategy aims to address potential inconsistencies that might arise post-merge into the 'master' branch, thus ensuring a persistent 'develop' branch at all times.
=> feat(CI): Add workflow for develop branch restoration

.github/workflows/create-develop-branch.yml
Introduce a new GitHub Actions workflow that triggers the creation of a 'develop' branch upon closure of a pull request to the 'master' branch.
This workflow is based on the assumption that a 'develop' branch is deleted automatically upon merging into 'master'. The integration of this workflow ensures that a current 'develop' branch always exists within the repository.
=> feat(CI): Add workflow for automatic develop branch creation

README.md
Improve README readability and condense extraneous information. Introduce new 'Infrastructure' and 'Tech Stack' sections for a concise overview of the repository.
=> refactor: Enhance README clarity and content

.github/workflows/create-develop-branch.yml
Add condition to abort creating the develop branch if it already exists. The workflow will only creates the develop branch whenever it does not exist.
=> feat(CI): Add condition to create develop branch workflow

components/icon/svgIcon/__test__/svgIcon.test.tsx, components/icon/svgLogo/__test__/svgLogo.test.tsx
Extend unit and integration test coverage for SvgLogo and SvgIcon components. The enhancements encompass various rendering scenarios to ensure comprehensive component behavior validation.
=> test: Extend SvgLogo and SvgIcon test coverage

.github/workflows/create-develop-branch.yml, .github/workflows/docker-image-build-push.yml
Modifications are made to the 'create-develop-branch' and 'docker-image-build-push' workflows to enhance their trigger conditions. The updated configuration ensures these workflows are activated only upon the closure of a pull request, subsequent to a successful merge.
=> refactor(CI): Enhance Workflow Triggers

components/label/labelList/__test__/labelList.test.tsx
Add the test for the LabelList component. This test covers the
=> test: Add the unit/integration test for the LabelList

components/label/labelList/labelItem/labelItemDropdown/dropdownContentOnClose/__test__/dropdownContentOnClose.test.tsx
A new integration test for the DropdownContentOnClose component has been added. The unique requirements of this component, given its derived state from the Recoil state management, necessitates a controlled testing environment. Through the application of `UserSessionEffect`, `mockedLabelItem`, and `demoLabelItem`, a structured environment for comprehensive component testing is effectively established.
=> test: Enhance Testing Suite with DropdownContentOnClose

README.md
The README document has been modified to reflect recent changes. The Container Registry badge has been removed and replaced with the Artifact Registry badge in light of the deprecation of Container Registry as of May 15, 2023.
An explanatory note has been included to clarify the rationale behind this badge replacement. Further updates encompass minor modifications to badge links and a rephrase of the introduction section for enhanced clarity.
=> feat: README Update

configs/securityHeaders.js
Refactor security headers to enhance protection, primarily by eliminating the inline-style from the security header directives. This update aims to uphold robust security practices and enhance application stability.
=> fix: Eliminate inline-style directive

.github/workflows/gcr-resources-optimization.yml, .github/workflows/recreate-develop-branch.yml, .github/workflows/run-tests.yml
Optimize GitHub Actions by modifying the nomenclature of associated files, aiming for increased clarity and improved comprehension. The alterations in the file names contribute to a more precise understanding of their respective functions.
=> feat: Revise GitHub Actions workflow names

.github/dependabot.yml, .github/workflows/gcr-resources-optimization.yml, .github/workflows/recreate-develop-branch.yml, .github/workflows/run-tests.yml
Update the update interval to weekly from daily.
=> feat: Update the dependabot's configuration

.github/workflows/github-actions-cache-cleanup.yml
Add the cache cleanup workflow for pull requests. The workflow is retrieved from the GitHub documentation on caching dependencies to speed up workflows.
Link to the GitHub documentation: [caching-dependencies-to-speed-up-workflows](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#managing-caches).
=> Add cache cleanup workflow for pull request

.github/workflows/github-actions-cache-cleanup.yml
Add a cache cleanup workflow for pull requests. 
Link to the GitHub documentation: [caching-dependencies-to-speed-up-workflows](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#managing-caches).
=> feat(CI): Add cache cleanup workflow for pull request

components/sections/homeContent/index.tsx, components/sections/homeHero.tsx, components/sections/underConstruction/index.tsx, components/todos/todoList.tsx, components/user/userDropdown/__test__/userDropdown.test.tsx, components/user/userDropdown/index.tsx, configs/securityHeaders.js, lib/stateLogics/utils/index.tsx, package-lock.json, package.json, tsconfig.json
In the development environment, `unsafe-inline` is added to the Next.js configuration under securityHeaders to ease debugging. Contrarily, it's removed in the production environment to enhance security.
The image loading mechanism has been transitioned from local optimization to CloudflareLoader. This modification enables image optimization capabilities of Cloudflare, promoting a reduction in image loading time.
=> feat: Adjust Next.js configurations

components/sections/homeContent/index.tsx, components/sections/homeHeader.tsx, components/sections/homeHero.tsx, components/sections/homeStartToday.tsx
Improve the Cumulative Layout Shift (CLS) by incorporating the SmoothTransition components. In the absence of a `useRef` reference, SmoothTransition component allows for immediate rendering, eliminating delays in animation and subsequently enhancing the CLS score.
=> fix: Address Cumulative Layout Shift issues

.github/workflows/gcr-resources-optimization.yml, .github/workflows/github-actions-cache-cleanup.yml, .github/workflows/run-tests.yml
Efficiency enhancements to the `run-tests` workflows have been achieved through improved dependency caching. A periodic cache cleanup has also been implemented, systematically purging all GitHub Actions caches every three days to ensure optimal resource management.
In addition, the `gcr-resources-optimization` now runs following the completion of the Google Cloud Run deployment. This adjustment increases consistency in maintaining the number of containers and revisions of resources.
=> refactor: Enhance efficiency and resource management in workflows

.github/dependabot.yml
Switch the weekly update to daily update.
=> chore: Update dependabot update interval

README.md
Update the outdated URL associated with the existing badge, ensuring its status reflects the most current information. Moreover, add a new badge specific to Cloudflare Image Optimization.
=> chore(doc): Update badge URLs and add the new badge

.github/workflows/workflow-run-cleanup.yml
Updates have been made to the workflow for better management of GitHub Action's resources. These updates target both caches and workflow run logs. Scheduled execution now takes place every five days, ensuring old workflow runs are regularly purged and all caches are maintained in a clean state.
=> chore(CI): Enhancements to workflow resource management

components/sections/homeContent/index.tsx
A resolution has been achieved for an issue that caused images to render
prematurely compared to headers. This solution involved the extraction of
the rate from the homeContent component, which successfully shortened the
rendering duration. As a consequence, the synchronization between image
transition and headers has been enhanced, rectifying the prior condition
where images rendered before text. Mobile view has shown substantial
enhancements due to these modifications.
=>   fix: Premature image rendering mitigation

public/service-worker.js
Service-worker's streaming capability has been improved by the addition of a fallback mechanism coupled with error handling. This activates when browser support for streaming is lacking.
=> refactor: Enhance service-worker stream with fallback

.github/workflows/docker-image-deploy.yml, components/ui/modals/labelModals/labelModal/index.tsx
The docker-image-deploy workflow run was updated, addressing a
necessary maintenance task. Also, font instability present in
labelModal was rectified, enhancing the UI's stability.
- fix: Correct font instability in labelModal (#803)
- chore: Update the docker-image-deploy workflow run (#802)
=> chore(merge): Update workflow run and correct font instability

.github/workflows/cleanup-cache.yml, .github/workflows/cleanup-workflow-runs.yml
Split the workflow run into separate ones to facilitate cache cleanup every 2 days and workflow cleanup every 20 days.
=> chore(CI):Separate cleanup workflow runs

components/icon/svgLogo/index.tsx, components/layout/layoutHeader/logo/__test__/logo.test.tsx
Incorporate unit and integration tests for the Logo component to ensure its functionality. Also, include tests evaluating the integration with the NetworkStatus component, achieving a more comprehensive validation of component interactions.
=> test: Enhance Logo component in Layout with tests

components/layout/layoutHeader/__test__/layoutHeader.test.tsx
Incorporate an integration test for the layoutHeader component. The test ensures proper rendering of child components and evaluates the effectComponent and userSessionEffect. Full testing of effectComponent's functions is omitted, as they will undergo comprehensive assessment in a dedicated set of tests.
=> test: Implement integration test for layoutHeader

components/layout/layoutFooter/footerBody/__test__/footerBody.test.tsx, components/layout/layoutFooter/footerBody/index.tsx
Incorporate integration tests to verify interactions with child components inside the FooterBody component. Additionally, include unit tests for FooterBody. Due to the unavailability of appropriate text or roles for querying, data-testids have been employed for elements within FooterBody.
=> test: Implement integration and unit tests for FooterBody component

components/layout/layoutFooter/sidebarTransition/__test__/sidebarTransition.test.tsx, components/ui/backdrops/backdrop/index.tsx
The implemented tests function as integration/unit tests, ensuring that the child component renders based on various conditions. Additionally, the tests verify that SidebarTransition renders the appropriate elements and classNames in response to different state updates.
For thorough testing, the testId attribute has been added to the BackDrop component.
=> test: Implement SidebarTransition component testing

components/layout/layoutFooter/__test__/layoutFooter.test.tsx
Implement integration tests for the LayoutFooter component, ensuring that child components render the appropriate text based on varying layout paths. These tests are essential for verifying that the corresponding navigation component is rendered on the appropriate path.
=> test: Implement integration tests for LayoutFooter component

package-lock.json, package.json
Update the package: next-router-mock.
=> chore: Update the package.

public/service-worker.js
Enhance service worker with prefetch. Prefetch is designed for resource fetching without utilization of the Cache Storage API, thereby relying on browser caching. Precache, already present but now more versatile, continues to leverage the Cache Storage API.
=> feat: Implement prefetch and precache options

components/sections/homeContent/index.tsx, components/sections/homeHero.tsx, components/sections/underConstruction/index.tsx, components/todos/todoList.tsx
Enhanced responsiveness of Image component via appropriate application of `sizes` props and `vw` values. This optimization leverages Cloudflare's image resizing services, facilitating faster and more efficient rendering due to reduction in image size, or matching image size more closely with display requirements.
=> refactor: Enhance Image component responsiveness

.github/workflows/cleanup-cache.yml, components/layout/layoutEffects/filterPathHomeEffect/__test__/filterPathHomeEffect.test.tsx, components/sections/footer.tsx
The cache cleanup workflow in GitHub Actions encountered errors linked
to the GitHub token. The workflow has been revised to eliminate these 
problems. Additionally, the frequency of the associated cron job has 
been adjusted to execute every 5 days, increased from the previous 
2-day interval.
=> fix: Resolve cache cleanup workflow issue

components/layout/home/layoutHomeLazy/__test__/layoutHomeLazy.test.tsx
Integration test appended to LayoutHomeLazy to verify proper mounting of effect components.
=> test: Supplement LayoutHomeLazy with new integration test

components/layout/app/appNavigation/appSidebarMenu/__test__/appSidebarMenu.test.tsx, components/layout/app/appNavigation/appSidebarMenu/index.tsx
An integration test is included in the AppSidebarMenu to examine the rendering of each router button and ensure that todosCount accurately displays the default count number. Additionally, readability in AppSidebarMenu is enhanced through refactoring.
=> test: Add integration test for AppSidebarMenu component

components/layout/app/appNavigation/__test__/appNavigation.test.tsx, components/layout/app/appNavigation/appSidebarMenu/index.tsx, components/layout/app/appNavigation/index.tsx, components/ui/buttons/disableButton.tsx, components/ui/buttons/iconButton/index.tsx, lib/data/options/button.tsx, lib/types/options/index.ts
Integration tests for AppNavigation components have been incorporated to validate the rendering and functionality of child components. In parallel, enhancements have been made to improve the readability of AppNavigation and DisableButton components. Furthermore, IconButton component now includes `data-testid` attribute for better testing access.
=> test: Incorporate integration tests for AppNavigation

components/layout/app/appNavigation/appSidebarMenu/__test__/appSidebarMenu.test.tsx, components/layout/layoutEffects/filterPathAppEffect/__test__/filterPathAppEffect.test.tsx, components/layout/layoutEffects/filterPathHomeEffect/__test__/filterPathHomeEffect.test.tsx
Address minor test issues including asynchronous warning outputs. Although primary tests are unaffected and do not cause any problems, warnings resulting from inadequate async/await handling are now handled appropriately.
=> fix: Rectify minor test issues and enhance async handling

components/layout/app/layoutAppLazy/__test__/layoutAppLazy.test.tsx, components/layout/app/layoutAppLazy/__test__/mockStateEffect.tsx, components/notifications/notification.tsx
Incorporate integration tests for LayoutAppLazy component that evaluate rendering of grouped effect components. Include mockStateEffect in the test file to simulate the state of the LayoutAppLazy component.
=> test: Add integration tests for LayoutAppLazy component

.github/dependabot.yml
Re-add the dependabot.yml to update the package automatically.
=> feat: Add the dependabot

components/section/homeContent/__test__/homeContent.test.tsx, components/section/homeContent/contentText/__test__/contentText.test.tsx, components/section/homeContent/index.tsx, components/section/section.consts.ts
Integration test implemented for HomeContent component to validate appropriate rendering of text prop in ContentText child component. Text values efficiently extracted to section.const for component and testing environment reuse.
Also includes refactoring of previous unit test, ContentText.test, with SmoothTransition mock setup to enhance testing workflow.
=> test: Extend HomeContent component test suite

components/section/homeStartToday/__test__/homeStartToday.test.tsx, components/section/homeStartToday/index.tsx, components/section/section.consts.ts
Establish unit and minor integration tests for HomeStartToday, targeting the rendering of content texts, SignInButton component, and gradient elements. These tests verify correct child component integration and proper rendering within the parent component.
=> test: Implement tests for HomeStartToday component

components/todos/todoList/todo/index.tsx, components/todos/todos.dynamicImports.ts
New module, todos.dynamicImports, has been added to collate todos related dynamic imports. Enhancement in readability and code structure is achieved through this addition.
=> feat: Introduce todos.dynamicImports module

app/globals.css, app/layout.tsx, app/v2/page.tsx
Add the globals.css and basic layout to the root of app router. Add the `v2` page to the app router for the smooth transition from the page router.
=> feat: Add the basic layout for the transition

.github/dependabot.yml
Add the time and timezone to the dependabot.
=> chore: Update the dependabot by adding timezone

app/globals.css, app/layout.tsx, app/v2/page.tsx, package-lock.json, package.json
Initialize migration from pageRouter to appRouter with basic setup:
- Jotai installation to replace Recoil
- globals.css addition
- Root layout inclusion
- Creation of v2 root appRouter page for smooth transition
=> feat: Prepare for appRouter migration

app/components/ui/button/button.types.ts, app/components/ui/button/buttonWithTooltip/index.tsx, app/components/ui/button/signInButton/__test__/signInButton.test.tsx, app/components/ui/button/signInButton/index.tsx, app/lib/lib.consts.ts
The SignInButton component has been appended to appRouter and pertinent integration tests have been incorporated. Moreover, the PATH_HOME constant assertion has been added to the universal constant location in `/lib/lib.const`.
=> feat: Append SignInButton component in appRouter

app/components/ui/button/buttonWithTooltip/__test__/buttonWithTooltip.test.tsx, app/components/ui/tooltip/__test__/tooltip.test.tsx
Supplement integration and unit testing for Tooltip text visibility. Additional tests focus on ButtonWithTooltip and Tooltip components, verifying proper rendering when visibility is enabled.
=> refactor: Supplement tests for Tooltip visibility

app/components/ui/container/container.types.ts, app/components/ui/container/divContainer/__test__/divContainer.test.tsx, app/components/ui/container/divContainer/index.tsx
Introduce DivContainer into appRouter. This client-side component is designed for use alongside server components. Accompanying unit test ensures accurate rendering of children elements and className attributes.
=> feat: Implement DivContainer in appRouter

app/components/ui/transition/transition.consts.ts, app/components/ui/transition/transition.utils.ts
Add the appRouter transition.consts and transition.utils to colocate the consts and utils with appRouter Transition components.
=> feat: Add new Transition consts and utils

app/components/ui/button/button.consts.ts, app/components/ui/transition/smoothTransition/index.tsx, app/lib/lib.utils.ts
Transition components.utils to lib.utils enhancing versatility of utility function application. Append STYLE constants to button.consts for reusable styling.
=> feat: Add appRouter button.consts and lib.utils

app/_lib/db/dbConnect.ts
Replace predecessor, databaseConnect of pageRouter, with enhanced dbConnect in /_lib/db/ to establish Mongoose database connectivity. Improvements entail superior error handling, effective connection management, and enriched connection options for optimized connection handling.
=> feat: Integrate improved dbConnect in appRouter

app/_lib/configs/envSchema.ts, app/api/auth/[...nextauth].ts, app/api/auth/_providers/index.ts, package-lock.json, package.json
Implementation includes introduction of multiple modules to enhance readability and maintainability of the code. Schema for environment variables is validated with a newly created envSchema, using the Zod library. Zod-Fetch has also been installed to accompany Zod. Furthermore, thorough error handling mechanisms are put in place.
=> feat: Implement NextAuth API endpoint in appRouter

app/_components/section/sectionContent/index.tsx, app/_components/section/sectionContent/sectionContentText/index.tsx, app/_components/section/sectionHeader/index.tsx, app/_components/section/sectionHero/index.tsx, app/_components/section/sectionStartToday/index.tsx, app/_components/ui/button/button.consts.ts, app/_components/ui/transition/smoothTransition/index.tsx, app/_lib/consts/style.consts.ts, app/_lib/utils/misc.utils.ts
Rename classNames utility function as mergeClasses to enhance distinctiveness in terminology. Ensures increased legibility and diminishes potential ambiguity arising from similarity between className and classNames.
=> refactor: Modify classNames utility function

app/_lib/utils/createConfigs.utils.ts
Enable createConfigs util functions to support object property access akin to standard object access.
=> feat: Improve the code with object property access

app/_lib/utils/configs.utils.ts
Resolve the issue with presetOptions not properly handling type errors when a non-existing property from Options is used within presetOptions. Type checking now accurately handles type errors. Additionally, performance has been enhanced by removing the spread operation, reducing overhead.
=> fix: Correct presetOptions in createConfigs util

app/_lib/utils/configs.utils.ts
Replace forEach with for loops to enhance looping performance.
=> refactor: Enhance performance of createConfigs

app/_components/section/sectionHero/__test__/sectionHero.test.tsx, app/_components/section/sectionHero/index.tsx, app/_components/section/sectionStartToday/__test__/sectionStartToday.test.tsx, app/_components/section/sectionStartToday/index.tsx, app/_components/ui/button/button.configs.ts, app/_components/ui/button/button.types.ts, app/_components/ui/button/signInButton/__test__/signInButton.test.tsx, app/_components/ui/button/signInButton/index.tsx
Update the configsSignInButton to include dynamic object values and inference types with the createConfigs utility function. All changes have been made.
=> refactor: Update configsSignInButton

app/_lib/utils/configs.utils.ts
Implement runtime error checking for nested objects, specifically targeting the 3rd level of nesting within the object.
=> feat: Enhance runtime error handling createConfig

jest.config.ts, package-lock.json, package.json
Install the new dev-dependency package: @swc/jest to improve Jest tests run faster.
=> chore(dev-dep): Install @swc/jest

app/_lib/utils/configs.utils.ts
Refactored createConfigs util function to enhance
readability. No significant functionality alterations.
=> feat: Refactor createConfigs util function

app/_lib/utils/configs.utils.ts
Rework createConfigs utility to enhance simplicity. Remove requiredOptions and nesting type constraints. Simplify TypeScript implementation. Retain string literal types to prevent type widening, eliminating need for enum or constant assertions. Enable automatic type checking.
=> feat: Simplify createConfigs function

app/_lib/utils/configs.utils.ts
Allow null and undefined within presetOptions and defaultOptions. Null values now explicitly map to null in output. Undefined values maintain previous behavior of omitting the property. Aimed at providing clearer function usage guidelines.
=> feat: Enhance createConfigs for null and undefined
