tpatalas/tp-next-todos

- lib/data/dataArrayOfObjects.tsx
- lib/data/dataTypesConst.tsx
- lib/dataConnections/indexedDB.ts
- lib/types/index.ts
IndexedDB will now automatically find and delete old versions whenever there is a version upgrade. Previously, the scope of deletion was limited to the current version minus one. However, since there may be multiple versioning jumps (e.g. upgrading from version 2 to version 5), the new deletion method ensures that any old version is deleted.
Note: Due to IndexedDB does not allow downgrading of the version, only lower versions will be considered.
> feat: add auto-deletion of old IndexedDB versions

- components/auth/authForm.tsx
- components/icons/svgLogo.tsx
- components/layouts/layoutApp/layout/index.tsx
- components/ui/buttons/button/svgLogoButton.tsx
- components/ui/dividers/divider/index.tsx
- lib/data/dataArrayOfObjects.tsx
- lib/data/dataTypesConst.tsx
- lib/data/stylePreset.tsx
- lib/models/User/index.ts
- lib/states/users/hooks.tsx
- lib/types/index.ts
- pages/api/v1/auth/[...nextauth].tsx
Add OAuth login for Google and Github. The sign-in process now includes the OAuth login for these providers as well as magic link email login.
The custom SvgLogoButton component was added to enable the OAuth login. This component renders a list of OAuth logins using an array of objects. Currently, the data set only includes Google and Github.
> feat: add the OAuth, Google and GitHub

- components/auth/authErrorMessage.tsx
- components/auth/authForm.tsx
- components/labels/labelItem.tsx
- components/ui/buttons/button/svgLogoButton.tsx
- lib/data/dataArrayOfObjects.tsx
- lib/data/dataTypesConst.tsx
- lib/states/todos/filterTodoIdsEffect.tsx
- lib/states/users/clientErrorMessageEffect.tsx
- lib/states/users/hooks.tsx
- lib/states/users/index.tsx
- lib/states/utils/hooks.tsx
- lib/types/index.ts
- pages/api/v1/auth/[...nextauth].tsx
Add the custom server-side error handling to NextAuth to render errors on the client when authentication fails, including for OAuth and email magic links.
The implementation removes unnecessary code, including state management for server-side errors, as NextAuth already provides an `errorId` that is
ready to use to cover error cases.
> feat: add custom server-side error handling to nextauth

- components/ui/dropdowns/v1/todoItemDropdown.tsx
- components/ui/inputs/checkbox.tsx
- components/ui/modals/todoModals/todoModal/todoModalHeaderButtons.tsx
- components/ui/tooltips/tooltips/index.tsx
- lib/data/dataOptions.tsx
- lib/data/dataTypesConst.tsx
With this fix, the kbd showing on the tooltip no longer displays on i mobile devices (including mobile and tablets), improving the user experience for mobile users.
Additionally, modifier keys (such as "Ctrl" and "Command") are now managed with typesConsts as `MODIFIER_KBD`, centralizing the management of keybinds and making it easier to maintain in the future.
> fix: manage modifier keys  and disable kbd on mobile devices

- configs/securityHeaders.js
- lib/states/effects/queryEffects.tsx
Resolved the issue where atomQueryLabels would fetch data on initial page load due to atomEffect's callback being executed faster than retrieving data from sessionStorage. The fix prioritizes demoFunction's condition check to prevent this behavior.
Additionally, remove the whitespace from contentSecurityPolicy.
> fix: fix atomquerylabels from fetching data on initial  load

- components/layouts/layoutApp/layout/layoutFooter/footerSidebar/index.tsx
Remove 'h-full' className from the element causing height conflict in footerSidebar. This change enables dynamic height calculation for other elements, fixing the previously restricted rendering.
> fix: resolve css rendering issue in footersidebar

- components/layouts/layoutApp/layout/layoutHeader/headerUser.tsx
- lib/dataConnections/indexedDB.ts
- lib/states/effects/atomEffects.tsx
- lib/states/effects/queryEffects.tsx
- lib/states/users/sessionDeactivateEffect.tsx
- lib/states/users/userSessionEffect.tsx
- lib/states/utils/index.tsx
This commit addresses an issue with the demo session triggering, which was caused by the `queryEffect` running before the session was set in sessionStorage. As a result, a null session value allowed `queryEffect` to bypass the expected condition.
The solution involves explicitly setting the session in sessionStorage and ensuring it persists between the user's offSession and actual session.
Additionally, to prevent users from deleting the session value in sessionStorage, the new session value is automatically set when the user removes it.
This approach improves session handling and resolves the demo fetching issue.
> fix: resolve demo fetching issue with session handling

- components/ui/inputs/floatingLabelInput.tsx
Add minor improvement to the balance of the floating input label. The label, which serves as the placeholder, was not centered correctly within the input, resulting in a subtle imbalance.
To address this, the label was repositioned slightly to improve its alignment with the input. Although the issue was subtle, this change helps improve the overall visual consistency of the input and ensures that the label is aligned properly.
> refactor: improve off position of floating input label

- lib/states/effects/queryEffects.tsx
- lib/states/labels/atomQueries.tsx
- lib/states/todos/atomQueries.tsx
- lib/types/index.ts
Remove demoFunctions from queryEffect to simplify its implementation and decouple demo-related logic from the session state. The session state now only deals with atoms and selectors with the 'query' suffix, such as `atomQueryTodoIds`.
Introduce demoAtoms to lay the foundation for a revamped demo-session. The demo-session will have a fully isolated state, ensuring seamless operation when no user session is available.
> feat: refactor queryEffect and introduce demoAtoms

- components/layouts/layoutApp/layout/layoutHeader/headerUser.tsx
- lib/states/users/index.tsx
- lib/states/users/userSessionEffect.tsx
- lib/states/utils/index.tsx
- pages/_app.tsx
Rename atomUserOffSession to atomUserSession to better represent the current user session. Update sessionStorage function to use sessionStorage instead of localStorageusage by for better consistency.
Refactor headerUser to accurately display the user's avatar. Restructure UserSessionEffect and move it to the `_app` component to receive the session state as early as possible.
> feat: refactor atomUserSession and UserSessionEffect

- lib/states/users/index.tsx
- lib/states/users/userSessionEffect.tsx
- lib/states/users/userSessionResetEffect.tsx
Update the `atomUserSession` atom to initially return a pending state instead of a default value. This provides two benefits:
- Prevents the atom from returning a false value when the session is undefined
- Reduces flickering caused by state changes, as many other atoms depend on the boolean value of `atomUserSession`, which gets its value from Next-Auth's session
> feat: optimize rendering by suppressing flickering

- pages/api/v1/labels/[labelId].tsx
- pages/api/v1/labels/index.tsx
- pages/api/v1/todos/[todoId].tsx
- pages/api/v1/todos/index.tsx
Previously, the GET request was not secured for development purposes. Now, the GET request returns an 'unauthorized access' message with a 401 status code when a request is made without a valid session. This improvement enhances the security of the API by preventing unauthorized information requests.
> feat: enhance security for API endpoint with GET request

- lib/data/dataTypesConst.tsx
- lib/models/Label/index.ts
- lib/models/Todo/TodoItems.ts
- lib/models/Todo/TodoNotes.ts
- lib/models/User/index.ts
- lib/states/utils/index.tsx
- pages/api/v1/labels/[labelId].tsx
- pages/api/v1/todos/[todoId].tsx
Implement a server-side retention policy at the API endpoint, with a default value of 7 days. When a user deletes an item (either a todo or a label), the item will be soft deleted and a retention policy will be applied. The item will then be completely removed from the database after 7 days.
This functionality can later be utilized to create a trashcan module, allowing users to set custom retention policies.
> feat: add server-side retention policy

- lib/models/Label/index.ts
- lib/models/Todo/TodoItems.ts
- lib/models/Todo/TodoNotes.ts
This commit addresses the issue where label updates would randomly fail
during PUT requests. The root cause was determined to be a database
conflict caused by indexing on the label's name through the `text`
field. By removing the index for the `text` field, the issue has been
resolved.
- fix: resolve label update failure on PUT requests (#422)
> fix: fix the label update issue

- lib/models/Label/index.ts
- lib/queries/queryLabels.ts
- lib/sanitizers/sanitizedSchemas.tsx
- pages/api/v1/labels/[labelId].tsx
- pages/api/v1/labels/index.tsx
- pages/api/v1/todos/[todoId].tsx
The primary cause of the issue was related to how data processing was handled on the server. Updating labels often involves an array of objects containing multiple values. Previously, updating each document with Promise.all() would randomly fail during the update process. The refactored code now utilizes updateMany() to correctly update multiple documents at once, resolving the issue.
> fix: resolve random label update failures

- deploy.sh
Resolve the deployment error caused by empty or unset VPC_CONNECTOR and VPC_REGION values in the .env.local file. The issue originated from the deploy.sh script always running with the VPC_FLAG. By removing the VPC_FLAG from the gcloud_run_deploy function call in deploy.sh, the issue is resolved, and deployments can proceed without errors when VPC_CONNECTOR and VPC_REGION are not provided.
Note: This issue was only occuring when deploying with deploy.sh command
> fix: resolve deployment error when VPC_CONNECTOR is empty

- .gitignore
- lib/models/Label/index.ts
- lib/models/Todo/TodoItems.ts
- lib/models/Todo/TodoNotes.ts
- pages/api/v1/labels/[labelId].tsx
- pages/api/v1/labels/index.tsx
- pages/api/v1/todos/[todoId].tsx
- pages/api/v1/todos/index.tsx
The issue occurred when updating multiple labels with the same value generated by `update.now()`, resulting in index key conflicts. To fix this, the index update has been removed from the schema, and the index was dropped manually using the MongoDB shell.
> fix: resolve label update failure due to index duplication

- components/layouts/layoutHeader/index.tsx
- components/layouts/layoutHeader/user.tsx
- lib/stateLogics/effects/atomEffects/atomEffects.tsx
- lib/stateLogics/states/layouts.tsx
- lib/stateLogics/states/misc.tsx
- lib/types/bases/effects.ts
Simplify the mediaQueryEffect by removing unnecessary types and props while retaining its core functionality. The mediaQueryEffect now only accepts a 'breakpoint' prop and returns a boolean. It returns 'true' for values higher than the breakpoint and 'false' for values lower than the breakpoint.
Additionally, apply minor CSS adjustments without altering the core structure.
> refactor: simplify mediaQueryEffect and adjust CSS

- components/layouts/app/index.tsx
- components/layouts/layoutFooter/index.tsx
- lib/stateLogics/effects/sidebarInitialEffect.tsx
- lib/stateLogics/states/layouts.tsx
- Rename atomSidebarOpen to atomSidebarInitialOpen for a more concise name.
- Remove mediaQueryEffect from atomSidebarInitialOpen, as it is irrelevant.
- Set atomSidebarInitialOpen's initial state to false (sidebar initially closed).
- Add SidebarInitialEffect component to enable the initial state to open.
> feat: update the sidebar initial state and effects

- prettier.config.js
Set `printWidth` to 100 instead of 120 for improved code structure readability.
> chore: update prettier settings

- components/labels/labelItem.tsx
- components/layouts/app/appNavigation/appSidebarMenu.tsx
- components/layouts/app/appNavigation/index.tsx
- components/layouts/app/index.tsx
- components/layouts/home/index.tsx
- components/layouts/layoutHeader/index.tsx
- components/layouts/layoutHeader/user.tsx
- lib/data/constAssertions/data.tsx
- lib/stateLogics/effects/userSessionEffect.tsx
- lib/stateLogics/states/atomEffects/labels.tsx
- lib/stateLogics/states/atomEffects/todos.tsx
- lib/stateLogics/states/misc.tsx
- lib/stateLogics/states/users.tsx
Replace atomUserSession with atomPathname for better rendering performance. Previously, atomUserSession received session data from Next-Auth's useSession hook, which is asynchronous and could cause flickering during rendering. Switching to atomPathname, which receives data from Next.js's useRouter's pathname, offers a synchronous and faster solution for setting state.
Note. The protection of the page is handled by middleware.
Additionally, incorporate Suspense and dynamic imports to optimize initial loading time and improve overall user experience.
> feat: enhance performance and user experiences

- lib/stateLogics/states/atomEffects/labels.tsx
- lib/stateLogics/states/atomEffects/todos.tsx
Enhance queryEffect by avoiding execution during off-session. Adjust the ternary operator condition to check for the pathname '/app' instead of 'demo', preventing unnecessary network requests.
> feat: optimize queryEffect and demoEffect handling

- components/todos/todo/todoItemFocuser.tsx
- components/ui/modals/labelModals/labelModal/index.tsx
- components/ui/modals/labelModals/labelModal/itemLabelModal.tsx
- components/ui/modals/todoModals/itemTodoModal.tsx
- pages/api/v1/todos/[todoId].tsx
This commit addresses a problem where the todoItem update would fail on the server when no label data was provided. The issue was caused by the session waiting for other data to be checked, resulting in undefined values being passed during the label update. The solution involved using a ternary operator to pass an empty array whenever no label data is provided, preventing undefined values from being passed and resolving the issue.
> fix: resolve todoItem update issue when no label data provided

- components/auth/authForm.tsx
- components/layouts/home/homeNavigation.tsx
- components/ui/dividers/dividerX.tsx
- components/ui/dividers/dividerY.tsx
- lib/data/constAssertions/data.tsx
- lib/stateLogics/hooks/layouts.tsx
- pages/contact/index.tsx
Add the Contact page using LayoutHome without any content. Update PATH_HOME, Contact link, and contact's htmlTitleTag accordingly. Refactor the Divider component to enhance reusability without altering its core functionality.
> feat: add Contact page and refactor Divider component

- components/sections/hero.tsx
- lib/data/stylePreset.tsx
- tailwind.config.ts
Implement a custom glow animation for a slow glow effect when used with a blur effect.
Add a new style preset, STYLE_BLUR_GRADIENT, which accepts three different colors to render the gradient.
> feat: add glow animation to hero section

- lib/stateLogics/hooks/misc.tsx
Add a new custom hook, useVerticalScrollPosition, to track the vertical scroll position as a numerical value. This hook enables dynamic style adjustments based on the scroll position within components.
> feat: Implement useVerticalScrollPosition custom hook

- components/layouts/home/homeNavigation.tsx
- components/layouts/layoutHeader/index.tsx
Resolve issues with the homeNavigation menu rendering on small screen sizes and when opening the mobile menu. Ensure proper background opacity and backdrop blur are applied on small screens, enhancing the user experience for mobile devices.
> fix: fix homeNavigation menu rendering on small screens

- components/sections/header.tsx
- components/sections/hero.tsx
- components/ui/gradients/labelsHorizontalGradients.tsx
- lib/stateLogics/hooks/misc.tsx
- lib/stateLogics/hooks/ui.tsx
- pages/index.tsx
This commit transitions the Header and Hero section components from client-side to server-side rendering. This change helps to avoid Flash of Unstyled Content (FOUC) or unnecessary loading spinners, resulting in a more seamless user experience.
Furthermore, custom hooks utilized within the Header and Hero section components have been reorganized into a new directory, /hooks/ui, for better code structure and maintainability. Previously, these hooks were located in the /hooks/misc directory.
> feat: Move Header and Hero components to server-side

- components/layouts/layoutFooter/index.tsx
- components/layouts/layoutHeader/index.tsx
Add a layer on top of the layout header for better alignment of the header menu and background colors.
Address the Flash of Unstyled Content (FOUC) issue in the mobile homeNavigation menu, which occurs when routing from the demo directory to the Home page, by conditionally assigning the 'hidden' class.
> feat: enhance layout header rendering and fix FOUC

- components/sections/homeContent.tsx
- components/sections/homeHeader.tsx
- components/sections/homeHero.tsx
- lib/data/constAssertions/data.tsx
- pages/index.tsx
Add the HomeContent section component, which contains a brief explanation of the application along with two images.
In addition, this commit renames the Header and Hero section components to HomeHeader and HomeHero, respectively, to better distinguish these specialized components.
> feat: add HomeContent section component and rename Header/Hero

- components/layouts/home/index.tsx
- components/sections/underConstruction/index.tsx
- lib/data/constAssertions/data.tsx
- pages/contact/index.tsx
- pages/features/index.tsx
- pages/implementations/index.tsx
- pages/pricing/index.tsx
Implement UnderConstruction component to display on all pages except the index (home) page. Add 'home-under-construction' image path to PATH_IMAGE_HOME as 'underConstruction'. Enhance user experience by providing a clear message and visual indication for pages under construction.
> feat: add UnderConstruction component to non-index pages

- components/layouts/home/homeNavigation.tsx
- components/layouts/home/index.tsx
- components/layouts/layoutFooter/footerNavigation.tsx
- components/layouts/layoutFooter/index.tsx
- components/layouts/layoutHeader/index.tsx
- components/layouts/layoutHeader/logo.tsx
- components/ui/backdrops/backdrop/index.tsx
- lib/data/stylePreset.tsx
- lib/stateLogics/effects/layout.tsx
- lib/stateLogics/hooks/layouts.tsx
improve the sidebarmenu on the layouthome by resetting its state whenever users route to the different page. initially this feature has not been added to reset the state of the layouthome's sidebarmenu.
additionally improve the backdrop of homelayout's sidebarmenu for better user experiences.
> feat: improve the sidebarmenu on layouthomey

- components/layouts/home/homeNavigation.tsx
- components/layouts/layoutFooter/footerNavigation.tsx
- components/layouts/layoutFooter/index.tsx
- components/layouts/layoutHeader/index.tsx
- components/layouts/layoutHeader/logo.tsx
- lib/stateLogics/effects/layout.tsx
- lib/stateLogics/hooks/layouts.tsx
- lib/stateLogics/states/layouts.tsx
Resolve the issue of the footer sidebar menu flashing briefly when navigating between 'app' and 'home' routes. The issue was caused by conditional rendering based on the layoutType without taking into account the sidebarOpen state. By incorporating an additional condition 'isSidebarOpen', the flashing behavior has been eliminated.
Additionally, this commit removes any unnecessary and unused code for better maintainability and readability.
> fix: fix flashing of sidebar menu during route transitions

- components/layouts/layoutHeader/user.tsx
Resolve an issue where user avatars from external sources, such as Google or GitHub, were not being rendered correctly on the initial page load. This was caused by a conditional check. Updating the logic to use a ternary operator now ensures that external avatars are properly loaded upon initial page load.
> fix: correctly load external user avatar on initial page load

- components/auth/authForm.tsx
Adjust the position and styles of the authform to ensure that it renders consistently and fully on all devices, including smaller screens.
Positioned the authform at 60% of the screen height on all devices. Tightened the spacing of the authform elements on smaller screens.
> feat: improve authform mobile layout

- components/sections/homeHeader.tsx
Resolve the validator warning related to the SmoothTransition component by properly placing the heading element inside it. This change ensures proper nesting and structure, improving overall code quality.
> fix: resolve validator warning

- lib/data/collections/footer.tsx
Update footer navigation menu to meet capitalization requirements. The previous version used some lowercase letters, but the new version capitalizes the first letter of each word for consistency and better readability.
> fix: fix the casing

- components/layouts/layoutHeader/signInButton.tsx
- components/ui/modals/modal/modalHeaders/headerDescription.tsx
Improve the performance of Next-Auth's SignIn call by prefetching the signIn page URL. This optimization may not be crucial in a development environment, but it is beneficial when serving cached landing pages.
Prefetching helps mitigate slow responses and redirection to the signIn page when users first interact with the application, as they might initially encounter a cached version without initiating a server start.
By prefetching the URL, the server is warmed up from a cold start, resulting in faster redirection and improved response handling.
> refactor: optimize Next-Auth SignIn call performance

- components/users/userSessionGroupEffect/__test__/userSessionGroupEffect.test.tsx
- components/users/userSessionGroupEffect/userSessionEffect/__test__/userSessionEffect.test.tsx
- components/users/userSessionGroupEffect/userSessionResetEffect/__test__/userSesionResetEffect.test.tsx
- components/users/userSessionGroupEffect/userSessionResetEffect/index.tsx
- lib/stateLogics/hooks/misc.tsx
- lib/stateLogics/utils/index.tsx
- package-lock.json
- package.json
This commit introduces unit tests for the Users module, following the transition to a colocation-based project structure. Key changes include:
- Add fake-indexeddb package for testing indexedDB functionality.
- Update RecoilObserverValue to return 'active' or 'inactive' based on the Recoil value, with null or undefined returning 'inactive'.
- Introduce testingOnlyAtom to return undefined if node is null in RecoilObserverValue, useful for various testing scenarios where a node might not be required.
- Rename RecoilObserver to RecoilObserverOnChange for clarity.
- Implement minor code improvements discovered during testing.
> test: add unit tests for Users module with updated structure

- components/notifications/__tests__/networkStatus.test.tsx
- components/users/user/__test__/user.test.tsx
- components/users/user/userDropdown/__test__/userDropdown.test.tsx
- components/users/userSessionGroupEffect/__test__/userSessionGroupEffect.test.tsx
- components/users/userSessionGroupEffect/userSessionEffect/__test__/userSessionEffect.test.tsx
- components/users/userSessionGroupEffect/userSessionResetEffect/__test__/userSesionResetEffect.test.tsx
- lib/stateLogics/utils/index.tsx
- lib/stateLogics/utils/testUtils.tsx
Create a new `testUtils` folder to enhance the management of test-related utilities. Move `RecoilObserverValues`, `RecoilObserverOnChange`, and `renderWithRecoilRoot` into the `testUtils` folder for better organization and efficiency.
> feat: improve test utilities organization

- components/notifications/__tests__/networkStatus.test.tsx
- components/users/user/__test__/user.test.tsx
- components/users/user/userDropdown/__test__/userDropdown.test.tsx
- components/users/userSessionGroupEffect/__test__/userSessionGroupEffect.test.tsx
- components/users/userSessionGroupEffect/userSessionEffect/__test__/userSessionEffect.test.tsx
- components/users/userSessionGroupEffect/userSessionResetEffect/__test__/userSesionResetEffect.test.tsx
- lib/stateLogics/utils/testUtils.tsx
Rename the `renderWithRecoilRoot` function to `renderRecoilRootAndSession`. The updated custom render function now includes both a `RecoilRoot` from Recoil and a `SessionProvider` from Next-auth, allowing it to accept an optional `session` parameter. This parameter can take either a `mockedSession` value or `null`, providing flexibility for testing in different environments.
> refactor: enhance custom render function with SessionProvider

- components/notifications/__tests__/networkStatus.test.tsx
- components/user/__test__/user.test.tsx
- components/user/userDropdown/__test__/userDropdown.test.tsx
- components/user/userSessionGroupEffect/__test__/userSessionGroupEffect.test.tsx
- components/user/userSessionGroupEffect/userSessionEffect/__test__/userSessionEffect.test.tsx
- components/user/userSessionGroupEffect/userSessionResetEffect/__test__/userSesionResetEffect.test.tsx
- lib/stateLogics/utils/testUtils.tsx
Update the function name from renderRecoilAndSession to renderWithRecoilAndSession to achieve better naming consistency and clarity in its purpose.
> refactor: rename renderRecoilAndSession function

- components/auth/auth.states.ts
- components/auth/authConfirmation/__test__/authConfirmation.test.tsx
- components/user/userSessionGroupEffect/userSessionResetEffect/__test__/userSesionResetEffect.test.tsx
- lib/stateLogics/utils/testUtils.tsx
Add unit tests to verify the functionality and reliability of the AuthConfirmation component. Enhance testingUtils by incorporating RecoilObserverSetValue, which allows for mocking specific conditions and manual state manipulation to create a tailored testing environment.
> test: implement unit tests for AuthConfirmation component

- components/auth/authConfirmation/__test__/authConfirmation.test.tsx
- components/auth/authEffect/authErrorMessageEffect.tsx
- components/auth/authForm/index.tsx
- components/user/userSessionGroupEffect/userSessionEffect/__test__/userSessionEffect.test.tsx
- components/user/userSessionGroupEffect/userSessionResetEffect/__test__/userSesionResetEffect.test.tsx
- lib/stateLogics/utils/testUtils.tsx
- Remove RecoilObserverOnChange component for simplicity
- Merge RecoilObserverValue and RecoilObserverSetValue into a single RecoilObserver component for better usability
- Integrate RecoilObserver directly into renderWithRecoilRootAndSession to allow seamless usage through options parameter when needed
> refactor: enhance renderWithRecoilAndSession function

- components/auth/authEffect/__test__/authErrorMessageEffect.test.tsx
This commit adds unit tests for the authErrorMessageEffect, specifically focusing on verifying that the error message is rendered correctly when users input an invalid email address. This ensures proper functionality and user experience for the authentication process.
> test: add unit tests for authErrorMessageEffect

- components/auth/auth.types.ts
- components/auth/authEffect/__test__/authErrorMessageEffect.test.tsx
- components/auth/authErrorMessage/__test__/authErrorMessage.test.tsx
- components/auth/authErrorMessage/index.tsx
- lib/types/bases/ui.ts
- lib/types/options/index.ts
Expand testing coverage for the AuthErrorMessage component, which is responsible for displaying both server-side and client-side error messages. The added tests primarily focus on verifying the accurate rendering of error messages based on different query parameters and error conditions.
> test: enhance AuthErrorMessage component test coverage

- components/auth/authForm/__test__/authForm.test.tsx
- components/auth/authForm/index.tsx
- Extend authForm test coverage to ensure comprehensive validation.
- Add hidden 'sr-only' text to SvgLogo component for improved accessibility and screen reader compatibility.
> test: enhance authForm tests and update the accessibility

- components/editor/editorComposer/__test__/editorComposer.test.tsx
- components/editor/editorEffect/editorAutoFocusEffect.tsx
- components/editor/todoEditor/__test__/todoEditor.test.tsx
This commit extends the testing suite by adding more integration tests for EditorComposer, incorporating the EditorAutoFocusEffect component. The tests were conducted using EditorComposer rather than EditorAutoFocusEffect due to its higher testing efficiency. i
Additionally, new tests have been added for TodoEditor, with missing tests such as conditional rendering checks of placeholder being handled within other component's integration tests to maintain efficiency.
> test: enhance testing for EditorComposer and TodoEditor

- package-lock.json
- package.json
Downgrade slate-react to v0.92.0 to resolve the placeholder delaying issue. Plans to replace slate with an alternative WYSIWYG library in the future.
> fix: Downgrade to slate-react@0.92.0

- components/ui/dropdowns/v1/calendarDropdown.tsx
- components/ui/modals/todoModals/todoModal/index.tsx
Addresses two issues related to DropdownCalendar.
First, resolves the
rendering issue behind TodoModal when the modal is open, caused by a stacking context issue due to the 'will-change: transform' property. The fix involves adding 'position: relative' and an appropriate 'z-index' value.
Second, adjusts the width of the DropdownCalendar button on smaller media queries to ensure it fits the right size.
> fix: Resolve DropdownCalendar rendering issues

- cloudbuild.yaml
- package.json
Enable conditional building with cloudbuild, allowing the build process to propagate only when on the master branch.
For non-master branches, the process triggers up to the testing steps. This prevents unnecessary deployments and ensures testing is performed for non-master branches.
> feat: Add conditional cloudbuild option

- .github/workflows/build-docker-image.yml
Introduce functionality to push the built Docker image to GitHub's Container Registry. As of now, the system utilizes GitHub's registry, providing a test as an alternative to Google's Container Registry.
Key advantages include cost efficiency and operational flexibility, notably during the execution of other workflows like testing.
Please note, the workflow structure may be subject to modifications in future updates.
> feat: Enable Docker Image Push to GitHub Container Registry

- .github/workflows/build-deploy-cloudrun.yml
- .github/workflows/cleanup-gcr-resources.yml
Introduces a new workflow for managing Google Cloud Run revisions. It offers the capability to specify the number of revisions to retain, configurable via an environment variable within the workflow itself. This flexibility allows developers to dictate the count of preserved environment variables as per their requirements.
Additionally, an unnecessary line in build-deploy-cloudrun has been removed.
> feat(CI): Implement Cloud Run Revision Cleanup Workflow

- .github/workflows/cleanup-gcr-resources.yml
Incorporates a fresh step into the workflow to handle removal of outdated images from the Container Registry, retaining only the last 5 images. This enhancement aids in maintaining a clean latest images within the Google Container Registry.
Also, for consistency, the environment variable names responsible for dictating the count of preserved resources have been updated. These environment variables now uniformly control the quantity of both revisions and images preserved in the Container Registry.
> feat(CI): Introduce Container Registry Image Cleanup Step

- .github/workflows/docker-image-build-push.yml
- .github/workflows/docker-image-deploy.yml
This commit separates the build-deploy-docker workflow into two separate workflows: build-push and deploy. This improves the maintainability of the project by making it easier to understand and update the workflows. The deploy workflow will wait for the build-push workflow to be completed before initiating.
Additionally, this commit removes the build-deploy-cloudrun workflow as it is no longer in use.
> feat: Separate the workflows of building and deploying docker

- components/icon/icon.const.ts
- components/icon/icon.types.ts
- components/icon/svgIcon/index.tsx
- components/icon/svgLogo/index.tsx
- components/layouts/layoutHeader/logo.tsx
- components/ui/buttons/button/svgLogoButton.tsx
- lib/data/collections/svgLogo.tsx
- lib/data/options/svg.tsx
- lib/types/bases/data.ts
- lib/types/bases/ui.ts
- lib/types/options/index.ts
Introduce `icon.types` for managing component icon-related type definitions, and `icon.const` for storing related constant assertions. Subsequent updates have been made to all subscribers for seamless integration with the new types and constant assertions.
> feat: Add icon.types and icon.const

- .github/workflows/docker-image-build-push.yml
- .github/workflows/docker-image-deploy.yml
In response to Google's official deprecation notice for Container Registry in 2024, CI/CD workflow has been updated to utilize Google Artifact Registry. Accommodating for Artifact Registry's specific repository name requirements, a new repository within the Google Cloud Platform is established. The repository name has been securely incorporated as a secret within our GitHub environment.
> feat(CI/CD): Transition Google Artifact Registry

- .github/workflows/cleanup-gcr-resources.yml
Google Artifact Registry (GAR) has replaced the soon-to-be deprecated Google Container Registry. The GitHub workflow for clearing Google Cloud Resources has been adjusted to accommodate this change.
Now, old images are purged from GAR rather than Google Container Registry. It is important to note that main features remain untouched.
> feat(CI): Rework Google Cloud Resource Cleanup Workflow

- .github/workflows/docker-image-deploy.yml
Adjustment made to the deploy-workflow where the `branches: [master]` directive was removed. This action addresses the issue of the deploy workflow failing to initiate following the completion of the build workflow.
> fix: Resolve deployment workflow interruption

- components/layouts/app/appNavigation/index.tsx
- jest.config.js
- tsconfig.json
Include the alias path of the label component within tsconfig and jest.config files. Moreover, update the alias path in the subscriber for a more streamlined path resolution, enhancing code maintainability.
> feat: Implement Label Alias Path in Configurations

- components/icon/icon.types.ts
- components/icon/svgIcon/index.tsx
- components/icon/svgLogo/index.tsx
- components/label/label.hooks.tsx
- components/ui/comboBoxes/labelComboBox.tsx
- components/ui/dropdowns/v1/labelComboBoxDropdown.tsx
- components/ui/dropdowns/v1/labelItemDropdown.tsx
- components/ui/modals/labelModals/labelModal/index.tsx
- components/ui/modals/labelModals/labelModal/itemLabelModal.tsx
- lib/data/constAssertions/ui.tsx
- lib/stateLogics/effects/comboBoxSelectedLabelsEffect.tsx
- lib/stateLogics/hooks/keybindings.tsx
- lib/stateLogics/hooks/modals.tsx
Transition all label-related hooks to label.hooks, promoting centralized and more efficient hook management. Also, eliminate unused const assertions to maintain a clean and clutter-free codebase.
> refactor: Relocate Label-related Hooks to label.hooks

- components/label/label.const.ts
- components/label/label.hooks.ts
- components/label/labelList/index.tsx
- components/label/labelList/labelItem/index.tsx
- lib/data/options/button.tsx
Transition various constants to label.const, ensuring a unified location for constants management. Further, implement appropriate renaming to maintain consistency in naming conventions.
> refactor: Relocate Constants to label.const

- .github/workflows/cleanup-gcr-resources.yml
- .github/workflows/docker-image-deploy.yml
Adjusts 'cleanup-gcr-resources' to retain only the three most recent resources, a reduction from the previous setting of ten.
In 'docker-image-deploy', multiple flags are modified:
- Add `--min-instances=1` to enhance the cold start time for Google Cloud Run.
- Add `--no-cpu-throttling` to establish 'CPU always allocated', leading to a 25% cost decrease in CPU and memory usage. Beneficial when a CPU is i continuously running, such as when min instance is greater than 0.
- Disable `--cpu-boost` by commenting it out, considering it does not offer extra benefits when the min-instances is above 0 and 'CPU always allocated' is in place.
> feat(CI/CD): Refine Github Actions Workflows

- components/label/label.const.ts
- components/label/labelList/labelItem/index.tsx
Extract and abstract the option properties for both PrefetchButton and LabelItemDropdown within the LabelItem component. This change enhances modularity and improves readability of the component code.
> ffrefactor: Extract options props within LabelItem component

- components/label/labelList/labelItem/index.tsx
- components/label/labelList/labelItem/labelItemButtonContent/index.tsx
- components/label/labelList/labelItem/labelItemDropdown/dropdownContentOnClose/index.tsx
- components/label/labelList/labelItem/labelItemDropdown/index.tsx
Decompose LabelItem component into smaller, more focused components to enhance readability, testability, and maintainability. Specific changes include:
- Abstract conditional className logic within LabelItem.
- Introduce LabelItemButtonContent as an isolated component.
- Move LabelItemDropdown component into LabelItem folder for better organization.
- Introduce DropdownContentOnClose as a specialized component within labelItemDropdown.
> refactor: Decompose LabelItem component

- components/label/labelList/__test__/labelList.test.tsx
- components/layouts/app/appNavigation/appSidebarMenu.tsx
- components/layouts/app/index.tsx
Incorporate null as the fallback in Suspense elements previously lacking any fallback. Enhances the code's readability and maintains consistency across the codebase.
> feat: Add null fallback to Suspense

- __mock__/label/index.ts
- components/icon/svgIcon/index.tsx
- components/label/labelList/labelItem/labelItemButtonContent/__test__/labelItemButtonContent.test.tsx
Expand the scope of testing for the LabelItemButtonContent component by introducing unit/integration tests. Utilizing a mockedLabelItem, located under the '/__mock__/label/', allows for effective mocking of labelItem.
In order to facilitate accurate testing, a 'data-testid' attribute has been introduced to the SvgIcon component. Recognizing that usage of 'data-testid' is typically reserved for cases where no other testing options are viable, it is necessary in this instance due to the SvgIcon being a decorative component without other distinct attributes or elements available for testing.
> test: Extend LabelItemButtonContent Testing

- components/label/labelList/__test__/labelList.test.tsx
- components/label/labelList/labelItem/labelItemDropdown/dropdownContentOnClose/__test__/dropdownContentOnClose.test.tsx
In an effort to streamline the testing process, the manual UserSessionEffect running alongside the test session has been removed. Given the existing `UserSessionEffect` component which effectively returns the Recoil state upon assessing the Next-Auth Session state, the need for manual repetition is eliminated.
While the presence of `UserSessionEffect` within the testing environment remains vital for accurate session state triggering, further inclusion proves redundant.
> feat(test): Refine testing methodology for efficiency

- components/label/label.const.ts
- components/label/labelList/labelItem/labelItemDropdown/index.tsx
Enhances readability and maintainability by abstracting options props within LabelItemDropdown. The resulting extracted values have been relocated to `label.const`. This change aids in code clarity and fosters a more modular approach.
> refactor: Refactor LabelItemDropdown component

- components/label/label.const.ts
- components/label/labelList/labelItem/labelItemDropdown/__test__/labelItemDropdown.test.tsx
- components/label/labelList/labelItem/labelItemDropdown/index.tsx
- lib/data/options/misc.tsx
The optionsLabelItemDropdown prop has been relocated into label.const for better maintainability. A new unit test has been added for LabelItemDropdown. This test does not run all the functional logics of each dropdown item, as this is a unit test. The actual implementation and integration will be covered within the integration test.
> test: Add unit test for LabelItemDropdown

- components/icon/icon.types.ts
- components/icon/svgIcon/index.tsx
In order to facilitate better testing, a data-testId option has been added to the SvgIcon component's properties. This enhancement is designed to ensure uniqueness of the testId across the test suite, contributing to more precise identification and isolation of this component during test execution.
> feat: Enhance SvgIcon component with optional testId property

- components/label/labelList/labelItem/__test__/labelItem.test.tsx
- components/label/labelList/labelItem/index.tsx
- components/label/labelList/labelItem/labelItemDropdown/__test__/labelItemDropdown.test.tsx
- components/ui/dropdowns/v1/dropdown/index.tsx
Incorporate an integration test for LabelItem, validating functional integrity with its child components. Given the complexities of Portal utilization within modal rendering, associated modals like LabelItemModal and LabelDeleteConfirmModal are mocked to facilitate successful integration testing.
> test: Implement integration test for LabelItem

- .github/workflows/docker-image-deploy.yml
The comments on the deploy arguments for Google Cloud Run were causing deployment failures due to unknown argument errors. This commit relocates the comments outside of the arguments, resolving the issue.
> fix: Relocate comments for docker-image-deploy

- .github/workflows/docker-image-deploy.yml
Address an issue originating from comment addition to gcloud deploy arguments. Previously, comments within gcloud deploy were mistakenly treated as arguments, leading to problems. The issue has been rectified by moving the comments outside of the gcloud deploy arguments.
> fix: Resolve workflow failure in `docker-image-deploy`

- configs/securityHeaders.js
- tsconfig.json
In the development environment, `unsafe-inline` is added to the Next.js configuration under securityHeaders to ease debugging. Contrarily, it's removed in the production environment to enhance security.
> feat: Adjust Next.js configurations

- jest.config.js
- tsconfig.json
Add alias path for Layout in `tsconfig` and `jest.config`. Purpose of this
change is to facilitate modular restructuring of the layout component. The
modification ensures ease of reference and provides a solid base for
future restructuring enhancements.
> feat: Add the alias path for Layout

- components/label/labelList/labelItem/__test__/labelItem.test.tsx
- components/layouts/app/index.tsx
- components/layouts/home/homeNavigation.tsx
- components/layouts/home/index.tsx
- components/layouts/layout.types.ts
- components/layouts/layoutFooter/footerNavigation.tsx
- components/layouts/layoutFooter/index.tsx
- components/layouts/layoutHeader/index.tsx
- components/layouts/layoutHeader/signInButton.tsx
- lib/stateLogics/effects/layout.tsx
- lib/stateLogics/hooks/layouts.tsx
- lib/stateLogics/states/layouts.tsx
- lib/types/bases/ui.ts
Renaming `layoutType` to `path` enhances clarity and aligns with coding conventions. The associated type definition now resides in a new file, layout.type, under the TypesLayout interface for better organization and readability.
> refactor: Rename `layoutType` and relocate type definition

- components/layouts/layout.utils.ts
- components/layouts/layoutHeader/signInButton.tsx
Rename the `layoutButtonOptionsHandler` to `optionsSignInButton`, and move to the new location: /layout/layout.utils.ts for better management.
> refactor: Update the layoutButtonOptionsHandler

- components/layout/layout.hooks.ts
Address an issue where mobileNavigation remained open upon route changes. The cause was due to the `useInitialNavigation` hook having dependencies, which led to state caching and consequently, the mobileNavigation persisting in the open state.
As the purpose of `useInitialNavigation` is to set the initial state of navigation for each render in the home layout, removing the dependencies successfully resolves the issue.
> fix: Resolve Mobile Navigation Rendering Issue

- components/layout/layoutFooter/footerNavigation/index.tsx
- components/layout/layoutFooter/index.tsx
- components/ui/backdrops/backdrop/index.tsx
- lib/stateLogics/states/layouts.tsx
Amend the rendering transition behavior of homeMobileNavigation which is targeted for mobile-sized media queries. The primary issue addressed is the incorrect transition effect, notably the absence of the expected rendering duration, causing the navigation menu to appear instantaneously.
The root cause is identified as a structural problem where the backdrop wasn't rendered appropriately because its state wasn’t in sync with the navigation menu’s state. By restructuring the backdrop as a child transition of the navigation menu, the issue is mitigated.
Additionally, small rendering issues have been rectified by eliminating conditional rendering that was initially intended to suppress routing between the app and home route. The resolution for this will be fully effective with the subsequent …
> fix: Refine homeMobileNavigation's rendering transition

- components/layout/app/layoutAppLazy/index.tsx
- components/layout/home/layoutHomeLazy/index.tsx
- components/layout/layoutEffects/bodyTagClassEffect/index.tsx
- components/layout/layoutEffects/initialNavigationEffect/index.tsx
- components/layout/layoutFooter/footerBody/index.tsx
- components/layout/layoutFooter/sidebarTransition/index.tsx
- lib/stateLogics/states/layouts.tsx
Resolve a flickering issue in the mobile navigation menu when transitioning between '/app' and '/' routes. The issue was traced back to a Recoil selector that was not updating promptly. Replacing the selector with atomNavigationOpen effectively mitigates the problem. Additionally, the commit streamlines the component props by utilizing atomLayoutType.
> fix: Resolve navigation transition glitch on mobile

- components/layout/layoutFooter/sidebarTransition/index.tsx
- components/ui/backdrops/backdrop/index.tsx
- package-lock.json
- package.json
The flickering of the homeNavigation transition backdrop stemmed from
a disparity in the leave duration of the backdrop transition compared to
the navigation transition. Reducing the leave duration of the backdrop
effectively mitigates the flickering. The commit also enhances the enter
and leave transition behavior of the navigationMenu.
> fix: Resolve homeNavigation transition backdrop flickering

- configs/securityHeaders.js
Add the image source URL to securityHeaders' 'connect-src' for pre-loading of external image URLs, enhancing webWorker's efficiency by fulfilling preloading requirements.
> chore: Update securityHeaders with image source URL

- components/layout/layout.hooks.ts
- configs/securityHeaders.js
Routing under '/app' was failing due to an incorrect module import.
'useRoute' was previously imported from 'next-router-mock' instead of
'next/router'. This has been corrected to restore proper routing for
'/app' and its related paths.
> fix: Correct Routing Issue under '/app'

- components/serviceWorker/serviceWorkerRegister/index.tsx
- configs/securityHeaders.js
- jest.config.js
- package.json
- pages/_app.tsx
- public/service-worker.js
- sw-postbuild.js
- tsconfig.json
Incorporate a service-worker to handle caching of static assets. The assets being cached include files under the `/_next/static` directory and all images. The aforementioned directory contains assets generated during the build process.
To streamline cache versioning, the build process includes the generation of a new version identifier which is embedded in server-worker.js to invalidate the cache when necessary.
> feat: Add service-worker for static asset caching

- public/service-worker.js
Switch service-worker's caching strategy to `stale-while-revalidate` from `cache first then network`. This change enhances performance by synchronizing data efficiently. The new strategy prioritizes serving from cache, falls back to network if cache is unavailable, and asynchronously updates the cache with the latest data fetched from the network. Such an approach provides significant improvements in user experiences.
> feat: Update the `service-worker` with a new cache strategy

- public/service-worker.js
Service-worker no longer caches images, delegating this task only to Cloudflare which optimizes and serves them via CDN. Despite potential response time improvements via service-worker caching, client storage size constraints, which vary for each client, make this approach less viable.
> refactor: Update service-worker to omit image caching

- components/serviceWorker/serviceWorkerRegister/index.tsx
- configs/securityHeaders.js
- jest.config.js
- lib/dataConnections/databaseConnection.ts
- package-lock.json
- package.json
- pages/_app.tsx
- public/service-worker.js
- sw-postbuild.js
- tsconfig.json
Service workers have been significantly enhanced with new caching 
strategies and stream fallback support. Additionally, project dependencies
have been updated, and database configuration options have been revised
to address deprecation.
- feat: Update the `service-worker` with a new cache strategy (#798)
- feat: Add service-worker for static asset caching (#786)
- refactor: Enhance service-worker stream with fallback (#800)
- refactor: Update service-worker to omit image caching (#799)
- chore: Update databaseConnection config for deprecated options (#797)
- build(deps): Bump @next/bundle-analyzer from 13.4.4 to 13.4.5 (#789)
- build(deps-dev): Bump eslint-config-next from 13.4.4 to 13.4.5 (#787)
- build(deps-dev): Bump @typescript-eslint/parser from 5.59.8 to 5.59.11 (#794)
- …
> chore(merge): Introduce service-worker 

- .github/workflows/docker-image-deploy.yml
Revise docker-image-deploy workflow by removing the "Always on allocated" option (also known as "no-cpu-throttling"). This adjustment aims to decrease costs. Even though "Always on allocated" grants a discount on CPU and memory utilization, its pricing advantage is insignificant without a substantial number of requests.
> chore: Update the docker-image-deploy workflow run

- components/ui/modals/labelModals/labelModal/index.tsx
Address issue of font instability in labelModal during and post-transition. Observed behavior was font exhibiting a shaking or slight movement once transition completed. Root cause was element unpreparedness for impending transition. Solution applied: addition of 'will-transition-transform', successfully resolving the issue.
> fix: Correct font instability in labelModal

- components/layout/layoutHeader/navigationButton/__test__/navigationButton.test.tsx
- components/layout/layoutHeader/navigationButton/index.tsx
- components/layout/layoutHeader/searchBar/__test__/searchBar.test.tsx
Incorporate unit tests for the navigationButton component, evaluating both the rendering process and the state updates upon button clicks. As part of these tests, modifications have been made to navigationButton to embed screen-reader only text within iconButton.
Additionally, tests for the searchBar component are deliberately omitted at this time, as the component is currently serving as a placeholder and does not possess its final implementation.
> test: Add navigationButton component testing

- components/layout/layoutFooter/sidebarNavigationWrapper/__test__/SidebarNavigationWrapper.test.tsx
- components/layout/layoutFooter/sidebarNavigationWrapper/index.tsx
Add a unit test to ensure that the SidebarNavigationWrapper component applies runtime styles as expected. To facilitate testing, a data-testid attribute has been added to the component's element.
> test: Add unit test for SidebarNavigationWrapper component

- components/layout/layoutEffects/layoutTypeEffect/__test__/layoutTypeEffect.test.tsx
Add a unit test for the LayoutTypeEffect component to validate whether it mounts properly as an effect component and to ascertain that the state is set accurately for the layout path. By ensuring the component's successful mounting and state accuracy, the functionality of the effect component is verified to meet expectations.
> test: Implement unit test for LayoutTypeEffect component

- components/ui/modals/confirmModal/index.tsx
- components/ui/modals/labelModals/labelModal/index.tsx
- components/ui/modals/modal/modalHeaders/headerDescription.tsx
- components/ui/modals/modal/modalHeaders/headerTitle.tsx
- components/ui/modals/todoModals/todoModal/index.tsx
- lib/data/options/button.tsx
Switch from overflow-scroll to overflow-auto to eliminate the visibility of the outline. Additionally, append `will-change: transform` property to the element that exhibits slight movement during transitions.
> fix: Resolve overflow-scroll and transition anomalies

- components/ui/modals/todoModals/todoModal/index.tsx
Remove the disableScrollEffect from the todoModal due to the fact that gives the inconsistency of the scroll behavior. By removing the disableScrollEffect component, the scrollbar stays consistent.
> fix: Fix the inconsistency behavior of scrollbar

- components/layout/home/index.tsx
- components/sections/homeContent/index.tsx
- components/sections/homeHeader.tsx
- components/sections/homeHero.tsx
- components/sections/homeStartToday.tsx
- components/sections/underConstruction/index.tsx
The inclusion of `w-screen` led to the manifestation of a horizontal scrollbar whenever a vertical scrollbar emerged, causing rendering inconsistency. Resolution involved the removal of `w-screen` from the containers.
Padding was appended to the top and bottom sections of the underConstruction component, allowing for the scrollbar to be displayed in advance.
> fix: Resolve client scrollbar inconsistency due to `w-screen`

- components/layout/layoutEffects/initialNavigationEffect/__test__/initialNavigationEffect.test.tsx
Implements a unit test for InitialNavigationEffect, focusing on validating conditional state updates upon component mount. The aim of this test is to verify the boolean output of atomLayoutNavigationOpen.
> test: Enhance InitialNavigationEffect with Unit Test

- components/sections/footer.tsx
Switched the `tpAtalas` > `tpatalas` on the footer component.
> fix: minor fix on the casing of the Github username

- components/layout/layoutEffects/filterPathHomeEffect/__test__/filterPathHomeEffect.test.tsx
A unit test for FilterPathHomeEffect has been added. The test focuses on validating the correct rendering of text based on the pathname. This ensures that the htmlTitleTag is correctly displayed.
> test: Implement unit test for FilterPathHomeEffect

- README.md
The dependency version of the badge for Jest in the README was not correctly displayed. This problem has been addressed, ensuring accurate representation of the Jest version.
> fix: Rectify Jest badge rendering in README

- components/layout/layoutEffects/filterPathAppEffect/__test__/filterPathAppEffect.test.tsx
Add a new unit test for FilterPathAppEffect, verifying HTML title text rendering for different routes. The test parallels the unit test for FilterPathHomeEffect, focusing specifically on pathnames that include `/app`.
> feat: Add unit test for HTML title rendering

- components/layout/layoutEffects/bodyTagClassEffect/__test__/bodyTagClassEffect.test.tsx
Incorporate a unit test for BodyTagClassEffect to verify the accurate rendering of className based on layoutType. Ensures proper application of className to the body document.
> test: Add unit test for BodyTagClassEffect rendering

- .github/workflows/run-tests.yml
- package.json
Modify Package.json to establish `test --watch` as default test command. For single-run tests, `test:once` is now available and `test:watch` has been removed Workflow for executing unit/integration tests updated to utilize `test:once`.
> refactor: Revise test command and associated workflow

- components/layout/home/homeNavigation/__test__/homeNavigation.test.tsx
- components/layout/home/homeNavigation/index.tsx
- lib/stateLogics/utils/testUtils.tsx
HomeNavigation component now possesses a data-testid for integration testing. `<MemoryRouterProvider>` has been appended to the default renderFunction to enable testing of next.js link component. Rendering, routing, and conditional classNames form the core areas of testing.
> test: Augment HomeNavigation with new integration test

- components/layout/home/__test__/home.test.tsx
- components/layout/layoutFooter/index.tsx
Add integration test ensuring child components render correctly within LayoutHome. Mock next/head in the test due to its inability to render in testing environment. For accurate testing, testid is added to LayoutFooter component.
> test: Add integration test for LayoutHome component

- .github/workflows/run-tests.yml
- package.json
Restore npm test configurations to their initial state. Running `npm run test` executes the test suite a single time. For continuous testing during development, employ `npm run test:watch`.
> refactor: Revert to original npm test configurations

- components/sections/homeHero.tsx
- components/sections/underConstruction/index.tsx
Improve rendering times of large images served initially by ensuring proper assignment of viewport dimensions. This optimization, which takes place within Cloudflare's edge servers, yields a performance enhancement of over 200ms for rendering. Additionally, the image width is scaled down from 2k pixels to 1k pixels, with no degradation in quality.
> fix: Optimize image rendering on initial server request

- components/auth/authEffect/__test__/__mock__/mockErrorMessageObserver.tsx
- components/auth/authEffect/__test__/authErrorMessageEffect.test.tsx
- components/label/labelList/labelItem/__test__/__mock__/mockInitialNavigationEffect.tsx
- components/label/labelList/labelItem/__test__/labelItem.test.tsx
- components/layout/app/layoutAppLazy/__test__/__mock__/mockStateEffect.tsx
- components/layout/app/layoutAppLazy/__test__/layoutAppLazy.test.tsx
- components/layout/home/layoutHomeLazy/__test__/__mock__/mockStateEffect.tsx
- components/layout/home/layoutHomeLazy/__test__/layoutHomeLazy.test.tsx
- components/layout/layoutEffects/initialNavigationEffect/__test__/__mock__/mockNavigationEffect.tsx
- components/layout/layoutEffects/initialNavigationEffect/__test__/initialNavigationEffect.test.tsx
- components/layout/layoutFooter/__test__/__mock__/mockSidebarOpenEffect.tsx
- components/layout/layoutFooter/__test__/layoutFooter.test.tsx
- components/layout/layoutFooter/footerBody/__test__/__mock__/mockFooterStateEffect.tsx
- components/layout/layoutFooter/footerBody/__test__/footerBody.test.tsx
- components/layout/layoutFooter/sidebarTransition/__test__/__mock__/mockSidebarTransition.tsx
- components/layout/layoutFooter/sidebarTransition/__test__/sidebarTransition.test.tsx
Implement a directory specific to mocks to enhance readability and organization of test suites.
Rename MockStateEffect to MockLayoutAppLazyEffect for more descriptive naming.
> refactor: Reorganize mock component and rename for clarity

- components/layout/app/todosCount/__test__/todosCount.test.tsx
- components/layout/app/todosCount/index.tsx
- components/layout/layout.types.ts
Conduct unit tests to ascertain whether TodosCount renders the number of todos accurately according to specified conditions. To enhance type usability, the Props of TodosCount component are renamed to PropsTodosCount and relocated to `layoutTypes`.
> test: Add unit tests for TodosCount component

- components/layout/app/__test__/app.test.tsx
- components/layout/app/todosCount/__test__/todosCount.test.tsx
Integration tests have been added for the LayoutApp component to ascertain that all child components render and function as anticipated. Additionally, a minor correction has been applied to resolve a console error in the TodosCount test, and a redundant test has been removed.
> test: Add integration tests for LayoutApp

- components/loadable/loadingSpinner/__test__/__mock__/mockSpinnerState.tsx
- components/loadable/loadingSpinner/__test__/loadingSpinner.test.tsx
- components/loadable/loadingSpinner/index.tsx
Add a unit test to verify the rendering of the LoadingSpinner component when the prop is provided. Also, include the data-testid attribute for improved testing execution.
> test: Add unit test for LoadingSpinner component

- components/loadable/errorState/__test__/errorState.test.tsx
- components/loadable/errorState/index.tsx
- components/loadable/loadable.consts.ts
Introduce a unit test for the ErrorState component to verify the error message. To enhance flexibility, the error message employs a constant variable instead of hardcoded text.
> test: Add unit test for ErrorState component

- components/loadable/loadable.types.ts
- components/loadable/loadingStates/__test__/__mock__/mockLoadingSkeleton.tsx
- components/loadable/loadingStates/__test__/loadingState.test.tsx
- components/loadable/loadingStates/index.tsx
Add a unit test to verify that the LoadingState component renders loadingSkeleton based on the provided props or condition. To facilitate testing, `data-testid` attributes have been added to the LoadingState component and MockLoadingSkeleton. Additionally, the redundant `delay` type has been removed.
> test: Add unit test for LoadingState component

- components/sections/homeContent/index.tsx
- components/sections/homeHero.tsx
- components/sections/underConstruction/index.tsx
- lib/data/constAssertions/data.tsx
Resize images and change formats from webp to png for augmented compatibility and versatility. Establish hotlink protection through external infrastructure, as opposed to direct implementation within the repository, allowing exclusive display for authorized connections.
> refactor: Enhance image sizes and switch formats

- .github/dependabot.yml
Add the prefix to `chore` instead of default of `build`.
> feat: Update the dependabot configs

- components/section/footer/__test__/footer.test.tsx
- components/section/footer/index.tsx
- components/section/section.consts.ts
- components/section/section.utils.ts
- components/ui/dividers/dividerX.tsx
- lib/data/collections/footer.tsx
Extend integration testing for Footer components to ensure correct rendering of child components and routing functionality.
As part of the testing improvements, relocate copyright text to `section.consts` for optimal testability. Furthermore, add `data-testid` attribute to DividerX component and DATA_FOOTER_SOCIAL for enhanced component identification during test runs.
> test: Extend Footer component integration tests

- __mock__/react/mockUseRef.ts
- components/section/homeContent/contentText/__test__/contentText.test.tsx
Add unit test to verify proper rendering of passed props in the ContentText component. The test mocks the component due to its reliance on user interaction for transition triggering.
Also, introduce mockRef to simulate the useRef hook of React. The mockRef is stored in the global mock directory.
> test: Add unit test for ContentText component

- components/section/section.consts.ts
- components/section/underConstruction/__test__/underConstruction.test.tsx
- components/section/underConstruction/index.tsx
Create unit tests for UnderConstruction, verifying the accurate rendering of content text and link button. For testing efficiency, content text has been relocated to section.consts from UnderConstruction component.
> test: Add tests for UnderConstruction component

- components/serviceWorker/serviceWorker.consts.ts
- components/serviceWorker/serviceWorkerRegister/__test__/__mock__/mockServiceWorkerRegister.tsx
- components/serviceWorker/serviceWorkerRegister/__test__/serviceWorkerRegister.test.tsx
- components/serviceWorker/serviceWorkerRegister/index.tsx
Implemented unit testing for the ServiceWorkerRegister component, focusing on serviceWorker registration upon component mounting. To improve testing utility, created mockServiceWorkerRegister for mimicking the registration process. Furthermore, relocated the path to service-worker.js to serviceWorker.consts, enabling precise reuse within both component and test environments.
> feat: Implement ServiceWorkerRegister unit test

- components/todos/todoList/todo/index.tsx
- components/todos/todoList/todo/todoItem/index.tsx
- components/todos/todoList/todo/todoItemFocuser/index.tsx
- components/todos/todos.types.ts
Relocate the Todos related props type from the components into todos.types for better maintainability and reusability.
> refactor: Abstract Prop types of Todos component

- components/editor/editor.hooks.ts
- components/label/label.hooks.ts
- components/label/label.states.ts
- components/layout/app/layoutAppLazy/__test__/__mock__/mockStateEffect.tsx
- components/layout/app/todosCount/index.tsx
- components/todos/todoList/index.tsx
- components/todos/todos.states.ts
- components/ui/buttons/iconButton/priorityButton.tsx
- components/ui/dropdowns/v1/calendarDropdown.tsx
- components/ui/dropdowns/v1/labelComboBoxDropdown.tsx
- components/ui/modals/minimizedModal.tsx
- lib/stateLogics/hooks/calendar.tsx
- lib/stateLogics/hooks/misc.tsx
- lib/stateLogics/hooks/modals.tsx
- lib/stateLogics/hooks/priorities.tsx
- lib/stateLogics/hooks/todos.tsx
- lib/stateLogics/states/priorities.tsx
Transitioned states pertinent to Todos into todos.states to enhance maintainability. Colocation structure now followed more closely.
> refactor: Relocate Todos-related states

- package-lock.json
- package.json
Installed Jotai library to substitute Recoil, initiating migration to Next.js' appRouter.
> chore: Install Jotai for Recoil substitution

- .github/workflows/cleanup-cache.yml
Now Github Actions will run to cleanup cache every 2 days instead of 5 days.
> chore: Update the cleanup-cache workflow

- app/components/transition/smoothTransition/__test__/smoothTransition.test.tsx
- app/components/transition/smoothTransition/index.tsx
- app/components/transition/smoothTransition/smoothTransition.data.ts
- app/components/transition/smoothTransition/smoothTransition.types.ts
- app/components/transition/transition.types.ts
- jest.config.js
- tsconfig.json
Transition initiation is now facilitated via the inclusion of SmoothTransition in appRouter using the 'use client' directive. While relocating the component, types have been simplified for improved maintainability.
A corresponding unit test is provided, employing a mock of SmoothTransition. Note that the actual transition behavior is not covered, as it falls under the scope of end-to-end, not unit, testing.
> feat: Add SmoothTransition component to appRouter

- app/components/tooltip/__test__/tooltip.test.tsx
- app/components/tooltip/index.tsx
- app/components/tooltip/tooltip.types.ts
Tooltip implementation now resides in appRouter via the 'use client' directive. Given Tooltip's inherent requirement for client-side interaction, designation as a client component supersedes server component status.
A supplementary unit test is incorporated, validating child element rendering.
> feat: Implement Tooltip in appRouter

- app/components/ui/button/__test__/button.test.tsx
- app/components/ui/button/button.types.ts
- app/components/ui/button/buttonWithTooltip/__test__/buttonWithTooltip.test.tsx
- app/components/ui/button/buttonWithTooltip/index.tsx
Add the Button and ButtonWithTooltip components. These components are client components with the `use client` directive. Additionally simple unit tests are added for each component.
> feat: Add the Button appRouter components

- app/components/ui/button/buttonWithTooltip/__test__/buttonWithTooltip.test.tsx
- app/components/ui/button/signInButton/__test__/signInButton.test.tsx
- app/components/ui/tooltip/__test__/tooltip.test.tsx
Eliminate console error triggered by state update warning in the test environment. This anomaly stems from non-asynchronous state updates in testing. Employing `findByText` as a replacement for `getByText` mitigates the complications.
> fix: Resolve console error in test environment

- app/components/ui/container/container.states.ts
- app/components/ui/container/divContainerWithRef/index.tsx
- app/components/ui/transition/smoothTransition/smoothTransition.types.ts
- app/components/ui/transition/smoothTransitionWithDivRef/__test__/smoothTransitionWithDivRef.test.tsx
- app/components/ui/transition/smoothTransitionWithDivRef/index.tsx
- app/components/ui/transition/transition.hooks.ts
Incorporated SmoothTransitionWithDivRef, a wrapper for the SmoothTransition component. Its role involves accepting divRef value via Jotai's atom. Accompanying unit tests have been included as well.
Moreover, relevant type definitions have been included in transition.types.
> feat: Add SmoothTransitionWithDivRef component

- app/components/section/sectionHero/__test__/sectionHero.test.tsx
- app/components/section/sectionHero/index.tsx
Embed base64Converter utility in SectionHero, fetching placeholder images as base64 encoded format. Function fetches original images at build time, scales down image size and quality via sharp library, minimizing final file size.
For integration testing, function is mocked ensuring seamless test transition.
Known limitation: Original images, once fetched, are cached permanently on server, only refetched during next build. Future modification of this functionality is plausible.
> fix: Modify SectionHero component test

- app/components/next/imageWithRemotePlaceholder/__test__/imageWithRemotePlaceholder.test.tsx
- app/components/next/imageWithRemotePlaceholder/imageWithRemotePlaceholder.types.ts
- app/components/next/imageWithRemotePlaceholder/index.tsx
- app/components/next/next.types.ts
- app/components/section/section.consts.ts
- app/components/section/sectionHero/__test__/sectionHero.test.tsx
- app/components/section/sectionHero/index.tsx
- app/components/section/sectionHero/sectionHero.consts.ts
- jest.config.js
- tsconfig.json
Integrates ImageWithRemotePlaceholder, a simplified wrapper for Image component. Its function is to auto-fetch original images from remote URLs, and encode these as base64 using a utility function, reducing file size and quality significantly to use it as blurDataURL. Includes a unit test for ImageWithRemotePlaceholder. Addition of alias path for Next component has been made in tsconfig and jest.config.
Additionally, SectionHero's integration test is adjusted to accommodate ImageWithRemotePlaceholder component.
> feat: Add ImageWithRemotePlaceholder component

- app/components/next/imageWithRemotePlaceholder/index.tsx
Enhancement includes readability improvement and introduction of remoteImageHandler function, responsible for remote image fetching and conversion. Absence of `placeholder` prop causes function to return undefined, preventing image fetching and conversion to base64.
Notably, importation of 'server-only' module prevents use within client components. This is crucial, as 'getBase64FromImageURL' is specifically designed for server-side processing.
> refactor: Enhance ImageWithRemotePlaceholder

- app/components/section/section.consts.ts
- app/components/section/sectionHeader/__test__/sectionHeader.test.tsx
- app/components/section/sectionHeader/index.tsx
Migrate HomeHeader from pageRouter to appRouter, now named SectionHeader. Incorporate server and client-side child components as part of this migration. Integration tests validate rendering of child elements. For improved testing, assign 'gradientPole-testid' to gradientPole element.
> feat: Transition HomeHeader to appRouter

- app/components/section/sectionHeader/__test__/sectionHeader.test.tsx
Correct console.error triggered during SectionHeader component unit testing. Asynchronous behavior, resolved by employing 'findByTestId' for test id retrieval.
> fix: Resolve console.error in SectionHeader test

- app/components/section/section.consts.ts
- app/components/section/section.types.ts
- app/components/section/sectionContent/index.tsx
- app/components/section/sectionContent/sectionContentText/__test__/sectionContentText.test.tsx
- app/components/section/sectionContent/sectionContentText/index.tsx
- app/components/ui/container/divContainerWithRef/index.tsx
Incorporate SectionContentText component, specific to SectionContent. SectionContent and SectionContentText components are refactored version of HomeContent and HomeContentText within pageRouter.
sectionContentTextContent consts added to section.const for reuse.
Include unit test for SectionContentText, validating rendering of text and component mounting.
DivContainerWithRef no longer dependent within useEffect, to execute side effect solely on component mounting.
> feat: Add SectionContentText in appRouter

- app/components/section/sectionContent/__test__/sectionContent.test.tsx
- app/components/section/sectionContent/index.tsx
- app/components/section/sectionHeader/index.tsx
- app/components/section/sectionHero/index.tsx
Incorporates the SectionContent component into appRouter, as a refactored variant of HomeContent from pageRouter. Ensures the validity of the change through integration tests, assessing the rendering of text content and mocked image component.
Enhances SectionHeader and SectionHero components with the inclusion of previously omitted className attributes.
> feat: Extend appRouter with SectionContent component

- app/components/section/sectionContent/index.tsx
- app/components/section/sectionContent/sectionContentText/index.tsx
- app/components/section/sectionHeader/index.tsx
- app/components/section/sectionHero/index.tsx
- app/components/ui/container/container.states.ts
- app/components/ui/container/container.types.ts
- app/components/ui/container/divContainerWithRef/__test__/divContainer.test.tsx
- app/components/ui/container/divContainerWithRef/index.tsx
- app/components/ui/transition/smoothTransition/smoothTransition.types.ts
- app/components/ui/transition/smoothTransitionWithDivRef/__test__/smoothTransitionWithDivRef.test.tsx
- app/components/ui/transition/smoothTransitionWithDivRef/index.tsx
- prettier.config.js
Transition atomDivRef to `atomFamily`, generating distinct cache atoms with new parameters. A cache expiration policy is in place with a 1-hour timestamp to curb memory leaks from infinite atom creation.
Changes are applied to DivContainerWithRef and
SmoothTransitionWithDivRef, both now use _id string for specific atomFamily activation.
Rendering performance and efficiency improvements are noted.
Modify Prettier settings by updating printWidth to 120 from 110.
> refactor: Optimize atomDivRef and Prettier setting

- app/components/section/section.types.ts
- app/components/section/sectionContent/index.tsx
- app/components/section/sectionContent/sectionContentText/__test__/sectionContentText.test.tsx
- app/components/section/sectionContent/sectionContentText/index.tsx
- app/components/section/sectionHero/index.tsx
Eliminate redundant background color from SectionHero components. Adjust SmoothTransition component's speed by increasing rate value, optimizing rendering pace. Integrate SectionContText component with SmoothTransitionWithDiv and DivContainerWithRef components, utilizing _id prop, enhancing transition rendering fluidity.
> refactor: Enhance Section component renderings

- app/components/section/section.consts.ts
- app/components/section/sectionHero/__test__/sectionHero.test.tsx
- app/components/section/sectionHero/index.tsx
- app/components/section/sectionHero/sectionHero.consts.ts
- app/components/section/sectionStartToday/__test__/sectionStartToday.test.tsx
- app/components/section/sectionStartToday/index.tsx
Implement SectionStartToday, functioning as a transitional component from HomeStartToday. Renamed `optionsSectionHeroSignIn` to `optionsSignInButton` for reusability across components, including SectionStartToday.
Supplement with integration tests for verifying child elements and component rendering.
> feat: Implement SectionStartToday in appRouter

- app/_components/ui/icon/icon.consts.ts
- app/_components/ui/icon/icon.types.ts
- app/_components/ui/icon/svgIcon/__test__/svgIcon.test.tsx
- app/_components/ui/icon/svgIcon/index.tsx
- jest.config.js
- tsconfig.json
PageRouter's SvgIcon component has been refashioned under appRouter with identical nomenclature. A rudimentary unit test verifying its correct rendering accompanies the change. The fresh SvgIcon component, now being a server component, has eliminated React.memo due to insufficient benefits it offers in this context.
In conjunction, alias paths for tsconfig and jest.config have been instituted, along with icon.consts and icon.types requisite for SvgIcon.
> feat: Implement SvgIcon in appRouter

- app/_components/ui/tooltip/index.tsx
- app/_components/ui/tooltip/tooltip.types.ts
Update the appRouter's Tooltip component with mergeClasses utility functions by replacing the deprecating classNames utility function.
> refactor: Update the appRouter Tooltip component

- app/_components/next/imageWithRemotePlaceholder/__test__/imageWithRemotePlaceholder.test.tsx
- app/_components/next/imageWithRemotePlaceholder/imageWithRemotePlaceholder.types.ts
- app/_components/next/imageWithRemotePlaceholder/index.tsx
- app/_components/section/section.consts.ts
- app/_components/section/section.types.ts
- app/_components/section/sectionContent/__test__/sectionContent.test.tsx
- app/_components/section/sectionContent/index.tsx
- app/_components/section/sectionContent/sectionContentText/__test__/sectionContentText.test.tsx
- app/_components/section/sectionContent/sectionContentText/index.tsx
- app/_components/section/sectionHeader/__test__/sectionHeader.test.tsx
- app/_components/section/sectionHeader/index.tsx
- app/_components/section/sectionHero/__test__/sectionHero.test.tsx
- app/_components/section/sectionHero/index.tsx
- app/_components/section/sectionStartToday/__test__/sectionStartToday.test.tsx
- app/_components/section/sectionStartToday/index.tsx
- app/_components/ui/icon/icon.types.ts
- app/_components/ui/icon/svgIcon/index.tsx
- app/_components/ui/transition/smoothTransition/index.tsx
- app/_components/ui/transition/smoothTransition/smoothTransition.types.ts
- app/_components/ui/transition/smoothTransitionWithDivRef/index.tsx
- app/_components/ui/transition/transition.types.ts
- app/_components/ui/transition/transition.utils.ts
Object props have been renamed to configs for improved naming clarity. Configurations will now be maintained under the filename `file.configs.ts` for streamlined management.
> refactor: Rename object props to configs

- app/_lib/utils/createConfigs.utils.ts
Add the createConfigs utility function for structured object creation that can be consumed as object props, inspired by the class-variants-authority library. Prior to server components, the function might have added unnecessary overhead and complexity. With server components, it can define the schema of multiple objects together, centralizing object management.
Note that nesting objects is intentionally unsupported to avoid further complexity, as maintaining object props is already intricate.
> feat: Add createConfigs utility function

- app/_components/next/imageWithRemotePlaceholder/index.tsx
- next.config.js
Comment out global custom imageLoader from next.configs. Some images require external fetching without imageLoader, but global custom imageLoader lacks settings to disable imageLoader on a sepcific imageLoader.
> fix: Revert global custom imageLoader in next.configs

- app/_components/section/sectionContent/index.tsx
- app/_components/section/sectionContent/sectionContentText/index.tsx
- app/_components/section/sectionHeader/index.tsx
- app/_components/section/sectionHero/index.tsx
- app/_components/section/sectionStartToday/index.tsx
- app/_components/ui/tooltip/index.tsx
- app/_components/ui/transition/smoothTransition/index.tsx
- app/_lib/consts/style.consts.ts
- app/_lib/utils/misc.utils.ts
Replace mergeClasses util with cx from class-variance-authority library. Functionality to merge classes remains consistent.
> refactor: Replace mergeClasses with cx

- app/_lib/utils/createConfigs.utils.ts
Modify the `createConfigs` util function by removing `for loop` tnd include a TypeScript wrapper that returns the return types of the configs function. Inspired by the class-variance-authority library, the new TypeScript capabilities in `createConfigs` significantly improve the DX. Once the object has been defined within createConfigs, each object will automatically generate the types, and these can be passed with the TypeScript wrapper for use.
> refactor: Enhance `createConfigs`

- app/_lib/utils/createConfigs.utils.ts
`createConfigs` util now allows optional value of null or undefined for defaultOptions properties. If a defaultOption's property is undefined or null, it will not appear in the final object. Providing an empty object as defaultOptions will result in no objects being passed to the final output, while omitting defaultOptions entirely will result in a type error. This functionality facilitates selective inclusion of properties in the options.
> feat: Enhance `createConfigs` util function

- app/_lib/utils/createConfigs.utils.ts
Include required options as array in `createConfigs` util, enforcing specification when the function is invoked. The `required` field remains optional, ensuring no impact on defaultOptions to prevent unnecessary additional overhead.
> feat: Add `required` to `createConfigs` utils

- app/_lib/utils/createConfigs.utils.ts
Previously, passing an argument to the createConfigs function was always mandatory, even if the required field was undefined or empty. The problem has been fixed, and using the function without the required field will no longer result in an error.
> fix: Resolve required field issue in createConfigs

- app/_lib/utils/configs.utils.ts
Remove mergeConfigs as its utilization lacks significant value in applications. Alter createConfigs to prevent direct nesting of objects or arrays, enforcing a specific structure. Increase in complexity has led to a constraint on direct nesting, though nesting via indirect means remains viable.
Extension of other configurations into createConfigs has not been restricted, recognizing its potential necessity. Nonetheless, it is advised to minimize such extensions within createConfigs to mitigate performance overhead.
> refactor: Modify createConfigs function

- jest.config.ts
- jest.setup.ts
- package-lock.json
- package.json
- tsconfig.json
Upgrade the @testing-library/jest-dom package to version 6.0.0, adapting to the breaking change. Convert jest.configs and jest.setup to TypeScript, and add the ts-node dependency to enhance testing capabilities.
> feat: Update dependencies including @testing-library/jest-dom

- app/_lib/utils/configs.utils.ts
Optimize the performance of createConfigs by enhancing the for loop. Now ensuring that preset values are overridden by explicit options if the explicit values are present.
Previously, preset values would override all types of values. Now, explicit values in a function call will override preset values. The new priority order is:
Explicit Options > Preset Options > Default Options.
> feat: Refine createConfigs function

- app/_lib/utils/configs.utils.ts
createConfigs util function now supports passing null or undefined as a value. Passing one of these values will remove the corresponding object property from the output, enhancing usability.
> feat: Update createConfigs util with new feature

- app/_lib/utils/configs.utils.ts
Update createConfigs to permit level 1 nesting while restricting level 2 and beyond. The change reflects the need to accommodate values that may be either arrays or objects, and previously, level 1 nesting was constrained by types. Now, only nesting beyond level 1 is limited.
> feat: Enable additional nesting in createConfigs

- app/_components/ui/transition/smoothTransitionWithDefaultConfigs/__test__/smoothTransitionWithDefaultConfigs.test.tsx
Address the console error stemming from asynchronous text look up in the test of smoothTransitionWithDefaultConfigs.
> fix: Resolve console error in the unit test

- app/_lib/utils/configs.utils.ts
Allow passing undefined or null to presetOptions within createConfigs util function. When undefined or null are passed, nothing is returned when the preset is used. Enhancing the handling of these values enables exemption of preset values from the object's output.
> feat: Enhance presetOption in createConfigs

- app/_lib/utils/configs.utils.ts
Enhance createConfigs to handle type errors with custom error messages for the initial values of the Options. Enforce object as the initial value for Options. Any non-object value, such as an array or a primitive, results in a type error.
> feat: Enhance createConfigs util with type error

- package-lock.json
- package.json
Downgrade to next@13.4.13 due to a new bug introduced in subsequent versions, causing environment variables to return undefined when standalone is used. Although the fix was implemented in next.js@13.4.19, another bug related to headless/react prevents upgrading. For the time being, version 13.4.13 will be used.
> fix: Correct Next.js docker environment issue

- app/api/auth/[...nextauth]/route.ts
The route's content has been missing. Re-added the content to route.ts.
> fix: Fix the missing next-auth's api route

- app/_lib/utils/configs.utils.ts
Modify createConfigs to enforce type constraints within options. Current implementation retains only object values.
> feat: Enhance type constraints in createConfigs

- app/api/auth/[...nextauth]/authOptions.ts
- app/api/auth/[...nextauth]/route.ts
Add the API route of NextAuth within appRouter. This is the only simple migration from the pageRouter.
> feat: Add the NextAuth API in appRouter

- app/_components/layout/logo/__test__/logo.test.tsx
- app/_components/layout/logo/index.tsx
- app/_components/section/sectionHero/__test__/sectionHero.test.tsx
- app/_components/section/sectionHero/index.tsx
- app/_components/ui/icon/icon.types.ts
- app/_components/ui/icon/svgIcon/__test__/svgIcon.test.tsx
- app/_lib/consts/assertion.consts.ts
- app/_lib/utils/test.utils.ts
- app/_lib/utils/test.utils.tsx
- jest.setup.ts
Introduces Logo component in appRouter, transitioning from pageRouter. Leverages NextAuth's getServerSession for server-side session access, eliminating the need for client-side hooks. Renames PATH_HOME to PATH_ROUTES and refactors renderAsyncComponent to renderAsync, adding nextLink option for compatibility with Link component.
> feat: Add Logo component to appRouter

- app/_components/ui/button/buttonWithTooltip/index.tsx
- app/_components/ui/button/index.tsx
- app/_components/ui/tooltip/index.tsx
Eliminates 'use client' directive to transition certain components to server-side. Such as Button component serving as root to server-side, retaining client-side scope for versions requiring onClick handlers.
> refactor: Transition client components to server

- app/_components/ui/icon/icon.types.ts
Previously, PropsSvgIcon utilized types inferred from configSvgIcon, resulting in restricted string literal types. Modified type definitions to allow widened string types, enhancing reusability and maintainability for primitive components like SvgIcon and Button.
> refactor: Revise PropsSvgIcon type definitions

- app/_components/section/sectionHero/__test__/sectionHero.test.tsx
- app/_components/section/sectionHero/index.tsx
- app/_components/section/sectionStartToday/__test__/sectionStartToday.test.tsx
- app/_components/section/sectionStartToday/index.tsx
- app/_components/ui/button/button.types.ts
- app/_components/ui/button/buttonWithTooltip/index.tsx
- app/_components/ui/button/index.tsx
- app/_components/ui/button/signInButton/__test__/signInButton.test.tsx
- app/_components/ui/button/signInButton/index.tsx
- app/_components/ui/button/signInButton/signInButton.configs.ts
- app/_components/ui/icon/icon.types.ts
- app/_components/ui/icon/svgIcon/index.tsx
Separate className from object props in configs for enhanced efficiency. Rename button.configs to signInButton.configs for clarity.
> refactor: Update className and button.configs
